-- generated by scc1

signature actors3 (
     use system;
     use converter;
     use binding;
     use parser;
     use lex;
     use arithmetic;
     use nets;
     use tokens;
     use err;
     use stdiop;
     use ctype;
     use stdio;
     use varstrings;
     use strings;
     use C;
     use actors;
     use basic;
     use structure;
     use objects;
     use GB;
);
