-- generated by scc1

signature ctype (
     use system;
     use strings;
     use stdio;
     import iseof(c:int):bool;
     import isdigit(c:char):bool;
     import isalpha(c:char):bool;
     import isalnum(c:char):bool;
     import isspace(c:char):bool;
     import iswhite(c:char):bool;
     import isnewline(c:char):bool;
     import isquote(c:char):bool;
     import isdigit(c:int):bool;
     import isalpha(c:int):bool;
     import isalnum(c:int):bool;
     import isspace(c:int):bool;
     import iswhite(c:int):bool;
     import isnewline(c:int):bool;
     import isquote(c:int):bool;
);
