Import('setLibSpecific',
       'setLibSpecificStateEnvExport','setLibSpecificConfigExport','setLibSpecificMakeExport','setLibSpecificMakeInstallExport','setLibSpecificNumStages','setLibSpecificStageCommandArguments',
       'setLibSpecificStageCommand','buildBuilders')

#set this to library name
libraryName = 'libxml2'
#Library specific declarations go here.
setLibSpecific('all','all','libxml2','downloadPath','ftp://xmlsoft.org/libxml2/')
setLibSpecific('all','all',libraryName,'CompressedLib','libxml2-2.7.8.tar.gz')
setLibSpecific('all',['linux-x86','linux-x86_64'],libraryName,'InstallFiles',['$SConsInstallPrefixPath/lib/libxml2.a','$SConsInstallPrefixPath/include/libxml2/libxml/parser.h'])
setLibSpecific('all','all',libraryName,'DecompressLib',True)
setLibSpecific('all','all',libraryName,'allowsystem',True)
setLibSpecific('all','all',libraryName,'systemcincludes',['libxml2/libxml/parser.h'])
setLibSpecific('all','all',libraryName,'systemlibs',['libxml2'])
setLibSpecificNumStages('all','all',libraryName,3)
setLibSpecificConfigExport('release',['linux-x86','linux-x86_64'],libraryName,'CFLAGS','-g -O2')
setLibSpecificConfigExport('debug',['linux-x86','linux-x86_64'],libraryName,'CFLAGS','-g -O0')
setLibSpecificConfigExport('all',['linux-x86','linux-x86_64'],libraryName,'CC','gcc')
setLibSpecificConfigExport('all',['linux-x86','linux-x86_64'],libraryName,'CXX','g++')
setLibSpecificStageCommandArguments('all',['linux-x86','linux-x86_64'],libraryName,0,['--prefix=$SConsInstallPrefixPath'])

buildBuilders(libraryName)
