

--- old format (commented out) ---
-- document {
--      Key => bFunction,
--      Headline => "b-function",
--      UL {
-- 	  {TO (bFunction, Ideal,List), " - for an ideal"},
-- 	  {TO (bFunction, Module,List,List), " - for a module"}
-- 	  }
--      }

doc ///
  Key
    bFunction
  Headline
    Bernstein-Sato polynomial of a $D$-module with respect to a weight
  Description
    Text
      See [@TO2 ("WeylAlgebras :: Works Cited", "OT01")@, Section 4].
    Text
      @UL {
	  {TO (bFunction, Ideal,List), " -- for an ideal"},
	  {TO (bFunction, Module,List,List), " -- for a module"}
	  }@
///

--- old format (commented out) ---
-- document {
--      Key => {
-- 	 IntRing,
-- 	 [bFunction,Strategy],
-- 	 NonGeneric,
--      	 TryGeneric
-- 	 },
--      Headline => "specify strategy for computing b-function",
--      UL {
-- 	  {BOLD "IntRing", " -- the simplest algorithm available.
--      	       The idea is to compute ", EM "in", SUB "(-w,w)", EM "(I) ", "
--      	       intersect it with ",
-- 	       EM {"k[t", SUB "1", ",...,t", SUB "n", "]"},
-- 	       "(", EM {"t", SUB "i", " = x", SUB "i", "D", SUB "i"}, ")",
--      	       "Call the ideal obtained ", EM "J", ".
-- 	       Finally ",
-- 	       EM {"J + (t", SUB "1",
-- 		    " + ... + t", SUB "n", "- s) \\cap k[s]"},
-- 	       " is generated by the b-function that we are looking for."
-- 	       },
-- 	  {BOLD "TryGeneric", " -- checks whether the ideal is generic
-- 	       and if that is the case uses Alg.5.1.5
-- 	       in Saito-Sturmfels-Takayama (1999) otherwise is equivalent
-- 	       to ", TT "NonGeneric",
--      	       },
-- 	  {BOLD "NonGeneric",
-- 	       " -- uses 5.1.6 in Saito-Sturmfels-Takayama (1999)"
-- 	       },
-- 	  {"Default:", BOLD "IntRing"}
-- 	  }
--      }

doc ///
  Key
    IntRing
    [bFunction, Strategy]
    NonGeneric
    TryGeneric
  Headline
    specify strategy for computing $b$-function
  Description
    Text
      @UL {
	  {TT "IntRing", TEX " -- the simplest algorithm available.
	       The idea is to compute $in_{(-w,w)}(I)$,
	       intersect it with
	       $k[t_1,\\ldots,t_n]$ ($t_i = x_i D_i$).
	       Call the ideal obtained $J$.
	       Finally $J + (t_1 + \\ldots + t_n - s) \\cap k[s]$
	       is generated by the $b$-function that we are looking for."
	       },
	  {TT "TryGeneric", " -- checks whether the ideal is generic
	       and if that is the case uses Algorithm 5.1.5
	       in [", TO2 ("WeylAlgebras :: Works Cited", "SST00"), "] otherwise is equivalent
	       to ", TT "NonGeneric"
	       },
	  {TT "NonGeneric",
	       " -- uses 5.1.6 in [", TO2 ("WeylAlgebras :: Works Cited", "SST00"), "]"
	       },
	  {"Default: ", TT "IntRing"}
	  }@
///


--- old format (commented out) ---
-- document {
--      Key => (bFunction, Ideal, List),
--      Headline => "b-function of an ideal",
--      Usage => "b = bFunction(I,w)",
--      Inputs => {
-- 	  "I" => {"a holonomic ideal in the Weyl algebra ",
-- 	       EM {"A", SUB "n", "(K)"}, "."},
-- 	  "w" => {"a list of integer weights corresponding
-- 	       to the differential variables in the Weyl algebra."}
-- 	       },
--     Outputs => {
-- 	  "b" => {"a polynomial ", EM "b(s)", " which is the b-function of ",
-- 	       EM "I", " with respect to ", EM "w"}
-- 	  },
--      "Use ", TO "setHomSwitch", "(true) to force all the subroutines
--      to use homogenized ", TO "WeylAlgebra",
--      PARA {
-- 	  BOLD "Definition. ", "The b-function ", EM "b(s)",
-- 	  " is defined as the monic generator
-- 	  of the intersection of ",
-- 	  EM {"in", SUB "(-w,w)", "(I)"}, " and ",
-- 	  EM "K[s]",
-- 	  ", where ",
-- 	  EM {"s = [w", SUB "1", "t", SUB "1", " + ... + w",
-- 	       SUB "n", "t", SUB "n", "]"},
-- 	  " (here ", EM {"t", SUB "i", " = x", SUB "i", "D", SUB "i"}, ")."},
--      EXAMPLE {
-- 	  "R = QQ[x_1,x_2,D_1,D_2,WeylAlgebra=>{x_1=>D_1,x_2=>D_2}]",
--      	  "I = ideal(x_1, D_2-1)",
--      	  "bFunction(I,{1, 0})",
--      	  },
--      Caveat => {
-- 	  "The ring of I should not have any parameters:
--      	  it should be a pure Weyl algebra. Similarly, this ring
-- 	  should not be a homogeneous ", TO "WeylAlgebra"
-- 	  },
--      SeeAlso => { "globalBFunction", "factorBFunction" }
--      }

doc ///
  Key
    (bFunction, Ideal, List)
  Headline
    $b$-function of an ideal
  Usage
    b = bFunction(I, w)
  Inputs
    I:Ideal
      a holonomic ideal in the Weyl algebra $D$
    w:List
      a list of integer weights corresponding to the differential variables in the Weyl algebra
  Outputs
    b:RingElement
      a polynomial $b(s)$ which is the $b$-function of $I$ with respect to $w$
  Description
    Text
      Use @TO "setHomSwitch"@(true) to force all the subroutines
      to use homogenized @TO "WeylAlgebra"@.

      @BOLD "Definition."@ The $b$-function $b(s)$
      is defined as the monic generator
      of the intersection of $in_{(-w,w)}(I)$ and $K[s]$,
      where $s = w_1 t_1 + \cdots + w_n t_n$
      (here $t_i = x_i D_i$).
    Example
      R = QQ[x_1,x_2,D_1,D_2,WeylAlgebra=>{x_1=>D_1,x_2=>D_2}]
      I = ideal(x_1, D_2-1)
      bFunction(I,{1, 0})
  Caveat
    The ring of $I$ should not have any parameters:
    it should be a pure Weyl algebra. Similarly, this ring
    should not be a homogeneous @TO "WeylAlgebra"@.
  SeeAlso
    globalBFunction
    factorBFunction
///

--- old format (commented out) ---
-- document {
--      Key => (bFunction, Module, List, List),
--      Headline => "b-function of a holonomic D-module",
--      Usage => "b = bFunction(M,w,m)",
--      Inputs => {
-- 	  "M" => {"a holonomic module over a Weyl algebra ",
-- 	       EM {"A", SUB "n", "(K)"}},
-- 	  "w" => {"a list of integer weights corresponding
-- 	       to the differential variables in the Weyl algebra"},
-- 	  "m" => {"a list of integers, each of which is
-- 	       the shift for the corresponding component"}
-- 	       },
--      Outputs => {
-- 	  "b" => {"a polynomial ", EM "b(s)", " which is the b-function of ",
-- 	       	EM "M", " with respect to ", EM "w",
-- 	       	" and ", EM "m"}
-- 	  },
--      "The algorithm represents ", EM "M", " as ", EM "F/N",
--      " where ", EM "F", " is free and ",
--      EM "N", " is a submodule of ", EM "F", ".
--      Then it computes b-functions ", EM {"b", SUB "i", "(s)"},
--      " for ", EM {"N \\cap F", SUB "i"}, " (i-th component of ", EM "F",
--      ") and outputs ",
--      EM {"lcm{ b", SUB "i", "(s-m", SUB "i",") }"},
--      EXAMPLE{
-- 	  "R = QQ[x, dx, WeylAlgebra => {x=>dx}]",
-- 	  "M = cokernel matrix {{x^2, 0, 0}, {0, dx^3, 0}, {0, 0, x^3}}",
-- 	  "factorBFunction bFunction(M, {1}, {0,0,0})",
-- 	  "factorBFunction bFunction(M, {1}, {1,2,3})"
--      	  },
--      Caveat => {
-- 	  "The Weyl algebra should not have any parameters.
--      	  Similarly, it should not be a homogeneous Weyl algebra"
-- 	  },
--      SeeAlso => { "globalBFunction", "factorBFunction" }
--      }

doc ///
  Key
    (bFunction, Module, List, List)
  Headline
    $b$-function of a holonomic $D$-module
  Usage
    b = bFunction(M, w, m)
  Inputs
    M:Module
      a holonomic module over a Weyl algebra $D$
    w:List
      a list of integer weights corresponding to the differential variables in the Weyl algebra
    m:List
      a list of integers, each of which is the shift for the corresponding component
  Outputs
    b:RingElement
      a polynomial $b(s)$ which is the $b$-function of $M$ with respect to $w$ and $m$
  Description
    Text
      The algorithm represents $M$ as $F/N$
      where $F$ is free and $N$ is a submodule of $F$.
      Then it computes $b$-functions $b_i(s)$
      for $N \cap F_i$ (i-th component of $F$)
      and outputs $\text{lcm}\{ b_i(s-m_i) \}$.
    Example
      R = QQ[x, dx, WeylAlgebra => {x=>dx}]
      M = cokernel matrix {{x^2, 0, 0}, {0, dx^3, 0}, {0, 0, x^3}}
      factorBFunction bFunction(M, {1}, {0,0,0})
      factorBFunction bFunction(M, {1}, {1,2,3})
  Caveat
    The Weyl algebra should not have any parameters.
    Similarly, it should not be a homogeneous Weyl algebra.
  SeeAlso
    globalBFunction
    factorBFunction
///

--- old format (commented out) ---
document {
     Key => {
	 [globalBFunction,Strategy],
	 ViaAnnFs,
     	 ReducedB
	 },
     Headline => "specify strategy for computing global $b$-function",
     UL {
	  {BOLD "IntRing, TryGeneric, NonGeneric",
	       " -- passed to ", TO "bFunction",  ", see ",
	       TO [bFunction,Strategy] },
	  {BOLD "ViaAnnFs", " -- computes ",
	       EM "J(s)=Ann(f", SUP "s", EM ")", " and then intersects ",
	       EM "J(s)+D[s]f}", " with ", EM "K[s]"},
	  {BOLD "ReducedB", " -- computes ", EM "b(s)/(s+1)",
	       " by taking the intersection of ",
	       EM "J(s)+D[s](f,df/dx1,...,df/dxn)", " with ", EM "K[s]",
	       ", then multiplies by ", EM "s+1", "."},
	  {BOLD "GeneralBernsteinSato", " -- calls ", TO "generalB", "{f}."},
	  {"Default: ", BOLD "GeneralBernsteinSato"}
	  }
     }

-- doc ///
--   Key
--     [globalBFunction, Strategy]
--     ViaAnnFs
--     ReducedB
--   Headline
--     specify strategy for computing global b-function
--   Description
--     Text
--       @UL {
-- 	  {BOLD "IntRing, TryGeneric, NonGeneric",
-- 	       " -- passed to ", TO "bFunction", ", see ",
-- 	       TO [bFunction,Strategy] },
-- 	  {BOLD "ViaAnnFs", " -- computes
-- 	       $J(s) = \text{Ann}(f^s)$ and then intersects
-- 	       $J(s) + D[s]f$ with $K[s]$"},
-- 	  {BOLD "ReducedB", " -- computes $b(s)/(s+1)$
-- 	       by taking the intersection of
-- 	       $J(s) + D[s](f, df/dx_1, \ldots, df/dx_n)$ with $K[s]$,
-- 	       then multiplies by $s+1$"},
-- 	  {BOLD "GeneralBernsteinSato", " -- calls ", TO "generalB", " {f}"},
-- 	  {"Default: ", BOLD "GeneralBernsteinSato"}
-- 	  }@
-- ///

--- old format (commented out) ---
-- document {
--      Key => {(globalBFunction,RingElement), globalBFunction},
--      Headline => "global b-function (else known as the Bernstein-Sato polynomial)",
--      Usage => "b = globalBFunction f",
--      Inputs => {
-- 	  "f" => {"a polynomial"}
-- 	  },
--      Outputs => {
-- 	  "b" => RingElement => {"the b-function ", EM "b(s)",  " in ", EM "Q[s]"}
-- 	  },
--      PARA {
-- 	  BOLD "Definition. ", "Let ",
-- 	  EM "D = A_{2n}(K) = K<x_1,...,x_n,d_1,...,d_n>",
-- 	  " be a Weyl algebra.
-- 	  The Bernstein-Sato polynomial of a polynomial f is defined
-- 	  to be the monic generator of the ideal of all polynomials ",
-- 	  EM "b(s)", " in ", EM "K[s]", " such that
-- 	  ", EM " b(s) f^s = Q(s,x,d) f^{s+1}", " where ", EM "Q",
-- 	  " lives in ", EM "D[s]."},
--      PARA {
-- 	  BOLD "Algorithm. ",
-- 	  "Let ",
-- 	  EM "I_f = D<t,dt>*<t-f, d_1+df/dx_1*dt, ..., d_n+df/dx_n*dt> ",
-- 	  "Let ", EM "B(s) = bFunction(I, {1, 0, ..., 0})",
-- 	  " where 1 in the weight that corresponds to ", EM "dt. ",
-- 	  "Then the global b-function is ", EM "b_f = B(-s-1)"},
--      EXAMPLE lines ///
-- 	  R = QQ[x]
--      	  f = x^10
--     	  b = globalBFunction f
-- 	  factorBFunction b
--      	  ///,
--      SeeAlso => { "bFunction", "factorBFunction", "generalB", "globalB" }
--      }

doc ///
  Key
    (globalBFunction, RingElement)
    globalBFunction
  Headline
    global $b$-function (also known as the Bernstein-Sato polynomial)
  Usage
    b = globalBFunction f
  Inputs
    f:RingElement
      a polynomial
  Outputs
    b:RingElement
      the $b$-function $b(s)$ in $\QQ[s]$
  Description
    Text
      @BOLD "Definition."@ Let $D = A_{2n}(K) = K\langle x_1,\ldots,x_n,dx_1,\ldots,dx_n\rangle$
      be a Weyl algebra.
      The Bernstein-Sato polynomial of a polynomial $f$ is defined
      to be the monic generator of the ideal of all polynomials
      $b(s)$ in $K[s]$ such that
      $b(s) f^s = Q(s,x,d) f^{s+1}$ where $Q$ lives in $D[s]$.

      @BOLD "Algorithm."@
      Let $I_f = D\langle t,dt\rangle \cdot \langle t-f, dx_1+\partial f/\partial x_1 \cdot dt, \ldots, dx_n+\partial f/\partial x_n \cdot dt\rangle$.
      Let $B(s) = \text{bFunction}(I, \{1, 0, \ldots, 0\})$
      where 1 is the weight that corresponds to $dt$.
      Then the global $b$-function is $b_f = B(-s-1)$.
    Example
      R = QQ[x]
      f = x^10
      b = globalBFunction f
      factorBFunction b
  SeeAlso
    bFunction
    factorBFunction
    generalB
    globalB
///

--- old format (commented out) ---
-- document {
--      Key => {(generalB,List,RingElement), (generalB,List), generalB},
--      Headline => "global generalized Bernstein-Sato polynomial",
--      Usage => "b = generalB(F,g), b = generalB F",
--      Inputs => {
-- 	  "F" => {"a list of polynomials"},
-- 	  "g" => {"a polynomial"}
-- 	  },
--      Outputs => {
-- 	  "b" => RingElement => {"the general Bernstein-Sato polynomial ",
-- 	       EM "b(s)",  " in ", EM "Q[s]"}
-- 	  },
--      "Bernstein-Sato polynomial for an arbitrary affine variety was introduced in ",
--      "Budur, Mustata, and Saito ", "``Bernstein--Sato polynomials of arbitrary varieties''. ",
--      "If the option ", TO "Exponent", " is specified, then the m-generalized Bernstein-Sato polynomial is computed. ",
--      "See ", EM "Berkesch and Leykin", " ``Algorithms for Bernstein-Sato polynomials and multiplier ideals'' for definitions.",
--      EXAMPLE lines ///
--      W = makeWA(QQ[x_1..x_3]);
--      factorBFunction generalB ({x_2^2-x_1*x_3, x_1^3-x_3^2}, x_2)
--      ///,
--      Caveat => {
-- 	  "The input could be either in a polynomial ring or the Weyl algebra. In the latter case the algebra
-- 	  should not have any central variables and should not be a homogeneous Weyl algebra."
-- 	  },
--      SeeAlso => { "bFunction", "globalBFunction", "lct", "multiplierIdeal" }
--      }

doc ///
  Key
    (generalB, List, RingElement)
    (generalB, List)
    generalB
  Headline
    global generalized Bernstein-Sato polynomial
  Usage
    b = generalB(F, g)
    b = generalB F
  Inputs
    F:List
      a list of polynomials
    g:RingElement
      a polynomial
  Outputs
    b:RingElement
      the generalized Bernstein-Sato polynomial $b(s)$ in $\QQ[s]$
  Description
    Text
      The Bernstein-Sato polynomial for an arbitrary affine variety was introduced in
      [@TO2 ("WeylAlgebras :: Works Cited", "BMS06")@].

      Passing the option @TT "Exponent => m"@ instead computes the
      @EM "m-generalized"@ Bernstein-Sato polynomial — a variant indexed by a
      positive integer $m$ that arises naturally in the study of multiplier
      ideals and V-filtrations. See [@TO2 ("WeylAlgebras :: Works Cited", "BL10")@] for definitions.
    Example
      W = makeWA(QQ[x_1..x_3]);
      factorBFunction generalB ({x_2^2-x_1*x_3, x_1^3-x_3^2}, x_2)
      factorBFunction generalB ({x_2^2-x_1*x_3, x_1^3-x_3^2}, x_2, Exponent => 2)
  Caveat
    The input could be either in a polynomial ring or the Weyl algebra. In the latter case the algebra
    should not have any central variables and should not be a homogeneous Weyl algebra.
  SeeAlso
    bFunction
    globalBFunction
    lct
    multiplierIdeal
///

--- old format (commented out) ---
document {
     Key => {[generalB,Strategy], InitialIdeal, StarIdeal},
     Headline => "specify strategy for computing generalized Bernstein-Sato polynomial",
     UL {
	  { BOLD "InitialIdeal",
	       " -- use the initial ideal in_{(-w,w)} Ann f^s; this Strategy is the fastest on many examples,
	       but can not be used with the ", TO "Exponent", " option." },
	  { BOLD "StarIdeal",
	       " -- use ``star ideal'', the (-w,w) homogeneous elements of the Ann f^s"}
	  },
     "See ", EM "Berkesch and Leykin", " ``Algorithms for Bernstein-Sato polynomials and multiplier ideals''."
     }

-- doc ///
--   Key
--     [generalB, Strategy]
--     InitialIdeal
--     StarIdeal
--   Headline
--     specify strategy for computing generalized Bernstein-Sato polynomial
--   Description
--     Text
--       @UL {
-- 	  { BOLD "InitialIdeal",
-- 	       " -- use the initial ideal $in_{(-w,w)} \text{Ann}\, f^s$; this strategy is the fastest on many examples,
-- 	       but cannot be used with the ", TO "Exponent", " option" },
-- 	  { BOLD "StarIdeal",
-- 	       " -- use ``star ideal'', the $(-w,w)$ homogeneous elements of $\text{Ann}\, f^s$"}
-- 	  }@

--       See Berkesch and Leykin, ``Algorithms for Bernstein-Sato polynomials and multiplier ideals''.
-- ///

--- old format (commented out) ---
-- document {
--      Key => {[generalB,Exponent], Exponent},
--      Headline => "specify exponent m for m-generalized Bernstein-Sato polynomial",
--      "See ", EM "Berkesch and Leykin", " ``Algorithms for Bernstein-Sato polynomials and multiplier ideals''."
--      }

doc ///
  Key
    [generalB, Exponent]
    Exponent
  Headline
    specify exponent $m$ for $m$-generalized Bernstein-Sato polynomial
  Description
    Text
      See [@TO2 ("WeylAlgebras :: Works Cited", "BL10")@].
///

--- old format (commented out) ---
-- document {
--      Key => ViaLinearAlgebra,
--      Headline => "an option for generalB=>Strategy",
--      "see ", TO "generalB"
--      }

doc ///
  Key
    ViaLinearAlgebra
  Headline
    a strategy value for @TO generalB@
  Description
    Text
      See @TO "generalB"@.
///

--- old format (commented out) ---
-- document {
--      Key => {(lct,Ideal), lct},
--      Headline => "compute the log canonical threshold for an ideal",
--      Usage => "l = lct I",
--      Inputs => {
-- 	  "I" => {"an ideal in a polynomial ring"}
-- 	  },
--      Outputs => {
-- 	  "l" => RingElement => {"a rational number, the log canonical threshold of ", EM "I"}
-- 	  },
--      EXAMPLE lines ///
--      QQ[x_1..x_3];
--      I = ideal (x_2^2-x_1*x_3, x_1^3-x_3^2);
--      lct I
--      ///,
--      SeeAlso => { "bFunction", "generalB" }
--      }

doc ///
  Key
    (lct, Ideal)
    lct
  Headline
    compute the log canonical threshold for an ideal
  Usage
    l = lct I
  Inputs
    I:Ideal
      an ideal in a polynomial ring
  Outputs
    l:QQ
      the log canonical threshold of $I$
  Description
    Text
      Computes the log canonical threshold of the ideal $I$ — the largest
      $c$ such that the multiplier ideal $J_I(c)$ equals the full ring.
    Example
      QQ[x_1..x_3];
      I = ideal (x_2^2-x_1*x_3, x_1^3-x_3^2);
      lct I
  SeeAlso
    bFunction
    generalB
///

--- old format (commented out) ---
-- document {
--      Key => [lct,Strategy],
--      Headline => "specify strategy for computing lct",
--      UL {
-- 	  {BOLD "ViaBFunction", " -- use ", TO "bFunction" },
-- 	  {BOLD "GeneralBernsteinSato", " -- use ", TO "globalB" }
-- 	  }
--      }

doc ///
  Key
    [lct, Strategy]
  Headline
    specify strategy for computing lct
  Description
    Text
      @UL {
	  {TT "ViaBFunction", " -- use ", TO "bFunction" },
	  {TT "GeneralBernsteinSato", " -- use ", TO "globalB" }
	  }@
///

--- old format (commented out) ---
-- document {
--      Key => GeneralBernsteinSato,
--      Headline => "a strategy option for lct, globalBFunction",
--      "see ", TO "lct", TO "globalBFunction", "."
--      }

doc ///
  Key
    GeneralBernsteinSato
  Headline
    a strategy option for lct, globalBFunction
  Description
    Text
      See @TO "lct"@ and @TO "globalBFunction"@.
///

--- old format (commented out) ---
-- document {
--      Key => ViaBFunction,
--      Headline => "a strategy option for lct",
--      "see ", TO "lct"
--      }

doc ///
  Key
    ViaBFunction
  Headline
    a strategy option for lct
  Description
    Text
      See @TO "lct"@.
///

--- old format (commented out) ---
-- document {
--      Key => {(factorBFunction, RingElement),factorBFunction},
--      Headline => "factorization of a b-function",
--      Usage => "bFunction b",
--      Inputs => {
-- 	  "b" => {"a polynomial obtained via one of the b-function routines"}
-- 	  },
--      Outputs => {
-- 	  Product => {"the factorization of ", TT "b"}
-- 	  },
--      BOLD "Fact. ", "The roots of any b-function are rational.",
--      EXAMPLE {
-- 	"R = QQ[x, dx, WeylAlgebra => {x=>dx}]",
--      	  "f = x^10",
--      	  "b = globalBFunction f",
--      	  "factorBFunction b"
--      	  },
--      Caveat => {
-- 	  "f should be an output of one of the b-function routines"
--      	  },
--      SeeAlso => {
-- 	  "bFunction",
-- 	  "globalBFunction"
-- 	  }
--      }

doc ///
  Key
    (factorBFunction, RingElement)
    factorBFunction
  Headline
    factorization of a $b$-function
  Usage
    factorBFunction b
  Inputs
    b:RingElement
      a polynomial obtained via one of the $b$-function routines
  Outputs
    :Product
      the factorization of @TT "b"@
  Description
    Text
      @BOLD "Fact."@ The roots of any $b$-function are rational.
    Example
      R = QQ[x, dx, WeylAlgebra => {x=>dx}]
      f = x^10
      b = globalBFunction f
      factorBFunction b
  Caveat
    The input should be an output of one of the $b$-function routines.
  SeeAlso
    bFunction
    globalBFunction
///

--- old format (commented out) ---
-- document {
--      Key => {(getIntRoots, RingElement), getIntRoots},
--      Headline => "get integer roots of a b-function",
--      Usage => "getIntRoots b",
--      Inputs => {
--      	  "b" => "the output of one of the b-function routines"
-- 	  },
--      Outputs => {
-- 	  List => {"the list of the integer roots of ", TT "b"}
-- 	  },
--      SeeAlso => {"globalBFunction", "bFunction"}
--      }

doc ///
  Key
    (getIntRoots, RingElement)
    getIntRoots
  Headline
    get integer roots of a $b$-function
  Usage
    getIntRoots b
  Inputs
    b:RingElement
      the output of one of the $b$-function routines
  Outputs
    :List
      the list of the integer roots of $b$
  Description
    Text
      Returns the list of integer roots of $b$. Useful for picking the
      shift exponent in $D$-module restriction and integration.
    Example
      R = QQ[x, dx, WeylAlgebra => {x=>dx}]
      b = globalBFunction(x^3)
      getIntRoots b
  SeeAlso
    globalBFunction
    bFunction
///

--- old format (commented out) ---
-- document {
--      Key => {(bFunctionRoots, RingElement), bFunctionRoots},
--      Headline => "get roots of a b-function",
--      Usage => "bFunctionRoots b",
--      Inputs => {
--      	  "b" => "the output of one of the b-function routines"
-- 	  },
--      Outputs => {
-- 	  List => {"the list of the roots of ", TT "b"}
-- 	  },
--      SeeAlso => {"globalBFunction", "bFunction", "generalB"}
--      }

doc ///
  Key
    (bFunctionRoots, RingElement)
    bFunctionRoots
  Headline
    get roots of a $b$-function
  Usage
    bFunctionRoots b
  Inputs
    b:RingElement
      the output of one of the $b$-function routines
  Outputs
    :List
      the list of the roots of $b$
  Description
    Text
      Returns all (complex) roots of $b$, not just the integer ones (cf. @TO getIntRoots@).
    Example
      R = QQ[x, dx, WeylAlgebra => {x=>dx}]
      b = globalBFunction(x^3)
      bFunctionRoots b
  SeeAlso
    globalBFunction
    bFunction
    generalB
///

--- old format (commented out) ---
-- document {
--      Key => {(globalB, Ideal, RingElement), globalB},
--      Headline => "compute global b-function and b-operator
--           for a D-module and a polynomial",
--      Usage => "H = globalB(I,f)",
--      Inputs => {
-- 	  "I" => {"a holonomic ideal"},
-- 	  "f" => {"a polynomial in a Weyl algebra
-- 	       (should not contain differential variables)"}
-- 	       },
--      Outputs => {
-- 	  "H" => HashTable => {"containing the keys ",
-- 	       TT "Bpolynomial", " and ", TT "Boperator"}
-- 	  },
--      "The algorithm used here is a modification of the original
--      algorithm of Oaku for computing Bernstein-Sato polynomials",
--      EXAMPLE lines ///
-- 	  R = QQ[x, dx, WeylAlgebra => {x=>dx}]
--      	  f = x^7
--      	  b = globalB(ideal dx, f)
--      	  factorBFunction b.Bpolynomial
--      	  ///,
--      SeeAlso => { "bFunction", "globalBFunction", "factorBFunction" }
--      }

doc ///
  Key
    (globalB, Ideal, RingElement)
    globalB
  Headline
    compute global $b$-function and $b$-operator for a $D$-module and a polynomial
  Usage
    H = globalB(I, f)
  Inputs
    I:Ideal
      a holonomic ideal
    f:RingElement
      a polynomial in a Weyl algebra (should not contain differential variables)
  Outputs
    H:HashTable
      containing the keys @TT "Bpolynomial"@ and @TT "Boperator"@
  Description
    Text
      The algorithm used here is a modification of the original
      algorithm of Oaku for computing Bernstein-Sato polynomials.
    Example
      R = QQ[x, dx, WeylAlgebra => {x=>dx}]
      f = x^7
      b = globalB(ideal dx, f)
      factorBFunction b.Bpolynomial
  SeeAlso
    bFunction
    globalBFunction
    factorBFunction
///

--- old format (commented out) ---
-- document {
--      Key => Boperator,
--      Headline => "a key attached by globalB and Dlocalize",
--      SeeAlso => { "globalB", "Dlocalize" }
--      }

doc ///
  Key
    Boperator
  Headline
    a key attached by globalB and Dlocalize
  SeeAlso
    globalB
    Dlocalize
///

--- old format (commented out) ---
-- document {
--      Key => Bpolynomial,
--      Headline => "a key attached by globalB",
--      "see ", TO "globalB"
--      }

doc ///
  Key
    Bpolynomial
  Headline
    a key attached by globalB
  Description
    Text
      See @TO "globalB"@.
///

--- old format (commented out) ---
-- document {
--      Key => {(globalBoperator, RingElement), globalBoperator},
--      Headline => "compute a b-operator of a polynomial",
--      SeeAlso => {"globalB"}
--      }

doc ///
  Key
    (globalBoperator, RingElement)
    globalBoperator
  Headline
    compute a $b$-operator of a polynomial
  Usage
    globalBoperator f
  Inputs
    f:RingElement
      a polynomial in a Weyl algebra (no differential variables)
  Outputs
    :RingElement
      the $b$-operator $P$ satisfying $P f^{s+1} = b(s) f^s$
  Description
    Text
      Convenience wrapper around @TO globalB@ that returns just the
      @TT "Boperator"@ component — the differential operator $P$ in the
      Bernstein functional equation.
    Example
      R = QQ[x, dx, WeylAlgebra => {x=>dx}]
      globalBoperator(x^3)
  SeeAlso
    globalB
    globalBFunction
///

--- old format (commented out) ---
-- document {
--      Key => {(localBFunction,RingElement,Ideal), localBFunction},
--      Headline => "local b-function (a.k.a. the local Bernstein-Sato polynomial)",
--      Usage => "b = localBFunction(f,P)",
--      Inputs => {
-- 	  "f" => {"a polynomial"},
-- 	  "P" => {"a (prime) ideal"}
-- 	  },
--      Outputs => {
-- 	  "b" => RingElement => {"the local b-function ", EM "b_P(s)",  " in ", EM "Q[s]"}
-- 	  },
--      PARA {
-- 	  "Computes the local b-function of f at P, if P is a prime ideal."
-- 	  },
--      Caveat => {"(feature) If P is not prime, computes the
-- 	  lcm of local b-functions over all primes containing P"},
--      	  EXAMPLE lines ///
-- 	  R = QQ[x,y]; f = x^2*(x+y+1); P = ideal(x,y);
--     	  b = localBFunction(f,P)
-- 	  factorBFunction b
--      	  ///,
--      SeeAlso => { "bFunction", "factorBFunction", "globalBFunction", "generalB", "globalB" }
--      }

doc ///
  Key
    (localBFunction, RingElement, Ideal)
    localBFunction
  Headline
    local $b$-function (a.k.a. the local Bernstein-Sato polynomial)
  Usage
    b = localBFunction(f, P)
  Inputs
    f:RingElement
      a polynomial
    P:Ideal
      a (prime) ideal
  Outputs
    b:RingElement
      the local $b$-function $b_P(s)$ in $\QQ[s]$
  Description
    Text
      Computes the local $b$-function of $f$ at $P$, if $P$ is a prime ideal.
    Example
      R = QQ[x,y]; f = x^2*(x+y+1); P = ideal(x,y);
      b = localBFunction(f,P)
      factorBFunction b
  Caveat
    If $P$ is not prime, computes the lcm of local $b$-functions over all primes containing $P$.
  SeeAlso
    bFunction
    factorBFunction
    globalBFunction
    generalB
    globalB
///

--- old format (commented out) ---
-- document {
--      Key => {(paramBpoly, RingElement, File), paramBpoly},
--      Headline => "compute the list of all possible Bernstein-Sato polynomials for a parametric polynomial",
--      Usage => "paramBpoly(f,file)",
--      Inputs => {
--      	  "f" => RingElement => {
-- 	       "a polynomial in Weyl algebra ", EM "A_n(Q)"
-- 	       },
-- 	  "file" => File => {"a file for TeX output (or stdio)"}
-- 	  },
--      Outputs => {
-- 	  List => {"all possible Bernstein-Sato polynomials"}
-- 	  },
--      "This function computes the finite list of all possible Bernstein-Sato polynomials
--      for a polynomial with parametric coefficients and creates latex code
--      describing strata in the parameter space
--      corresponding to the B.-S. polynomials --- each stratum is a constructible set. ",
--      "This is an implementation of the algorithmic approach in ",
--      EM {"Anton Leykin. Constructibility of the Set of Polynomials with a Fixed Bernstein-Sato Polynomial: an Algorithmic Approach.
--      Journal of Symbolic Computation, 32(6):663-675, 2001."},
--      EXAMPLE lines ///
-- 	  A =  (QQ [a,b,c]) [x, y, Dx, Dy, WeylAlgebra => {x=>Dx, y=>Dy}]
--      	  paramBpoly(a*x^2 + b*x*y + c*y^2, stdio)
-- 	  ///,
--      Caveat => {
-- 	  "A finite field ZZ/p is used to speed up computations.
-- 	  Option ", TT {"\"ground field\""}, " may be used to change the characteristic p.
-- 	  If p=0 the computation will be attempted over QQ."
-- 	  },
--      SeeAlso => {"globalBFunction"}
--      }

doc ///
  Key
    (paramBpoly, RingElement, File)
    paramBpoly
  Headline
    compute the list of all possible Bernstein-Sato polynomials for a parametric polynomial
  Usage
    paramBpoly(f, file)
  Inputs
    f:RingElement
      a polynomial in Weyl algebra $D$
    file:File
      a file for TeX output (or @TT "stdio"@)
  Outputs
    :List
      all possible Bernstein-Sato polynomials
  Description
    Text
      This function computes the finite list of all possible Bernstein-Sato polynomials
      for a polynomial with parametric coefficients and creates LaTeX code
      describing strata in the parameter space
      corresponding to the Bernstein-Sato polynomials --- each stratum is a constructible set.

      This is an implementation of the algorithmic approach in [@TO2 ("WeylAlgebras :: Works Cited", "Ley01")@].
    Example
      A = (QQ [a,b,c]) [x, y, Dx, Dy, WeylAlgebra => {x=>Dx, y=>Dy}]
      paramBpoly(a*x^2 + b*x*y + c*y^2, stdio)
  Caveat
    A finite field @TT "ZZ/p"@ is used to speed up computations.
    Option @TT "\"ground field\""@ may be used to change the characteristic $p$.
    If $p = 0$ the computation will be attempted over $\QQ$.
  SeeAlso
    globalBFunction
///
