Import('setLibSpecific',
       'setLibSpecificStateEnvExport','setLibSpecificConfigExport','setLibSpecificMakeExport','setLibSpecificMakeInstallExport','setLibSpecificNumStages','setLibSpecificStageCommandArguments',
       'setLibSpecificStageCommand','buildBuilders')
#set this to library name
libraryName = 'factory'
#Library specific declarations go here.
setLibSpecific('all','all','factory','downloadPath','ftp://www.mathematik.uni-kl.de/pub/Math/Singular/Factory/')
setLibSpecific('all','all',libraryName,'CompressedLib','factory-3-1-3.tar.gz')
setLibSpecific('all',['linux-x86','linux-x86_64'],libraryName,'InstallFiles',['$SConsInstallPrefixPath/lib/libsingfac.a'])
setLibSpecific('all',['Darwin-x86','Darwin-x86_64'],libraryName,'InstallFiles',['$SConsInstallPrefixPath/lib/libcf.a'])
setLibSpecific('all','all',libraryName,'DecompressLib',True)
setLibSpecific('all','all',libraryName,'Dependencies',['ntl'])
setLibSpecificNumStages('all','all',libraryName,3)
setLibSpecificConfigExport('all',['linux-x86','linux-x86_64'],libraryName,'CC','gcc')
setLibSpecificConfigExport('all',['linux-x86','linux-x86_64'],libraryName,'CXX','g++')
setLibSpecificMakeExport('all',['Darwin-x86_64'],libraryName,'CC','gcc -m64')
setLibSpecificMakeExport('all',['Darwin-x86_64'],libraryName,'CXX','g++ -m64')
setLibSpecificConfigExport('release',['linux-x86','linux-x86_64','Darwin-x86_64'],libraryName,'CXXFLAGS','-g -O2')
setLibSpecificConfigExport('release',['linux-x86','linux-x86_64','Darwin-x86_64'],libraryName,'CFLAGS','-g -O2')
setLibSpecificConfigExport('debug',['linux-x86','linux-x86_64','Darwin-x86_64'],libraryName,'CXXFLAGS','-g -O0')
setLibSpecificConfigExport('debug',['linux-x86','linux-x86_64','Darwin-x86_64'],libraryName,'CFLAGS','-g -O0')
setLibSpecificConfigExport('all',['linux-x86','linux-x86_64','Darwin-x86_64'],libraryName,'CPPFLAGS','-I$SConsInstallPrefixPath/include/ -DNDEBUG -DMP_INT=__mpz_struct -Dmpz_div_2exp=mpz_fdiv_q_2exp -Dmpz_div_ui=mpz_fdiv_q_ui -Dmpz_div=mpz_fdiv_q')
setLibSpecificConfigExport('all',['linux-x86','linux-x86_64','Darwin-x86_64'],libraryName,'LDFLAGS','-L$SConsInstallPrefixPath/lib/')
setLibSpecificStageCommandArguments('all','all',libraryName,0,['--enable-NTL','--prefix=$SConsInstallPrefixPath'])
setLibSpecific('all','all',libraryName,'patchfile','../../../../../libraries/factory/patch-3.1.3')
   
buildBuilders(libraryName)
