.SUFFIXES : .m2 .okay
.m2.okay:
	..\d\Release\Macaulay2.exe -silent $*.m2 -eexit(0)
	echo okay > $@

!ifdef HAVE_FILES
!include files.tmp
tests: $(FILES:.m2=.okay)
!endif

all: files.tmp
	$(MAKE) -k -f Makefile.NT HAVE_FILES=1 -nologo tests

files.tmp : *.m2
	echo FILES = $** > files.tmp
