export {

   "PolyhedralObject", 
-- Cone object with associated methods:
   "Cone", 
   "coneFromVData",
   "coneFromRays" => "coneFromVData", 
   "coneFromHData",
   "coneFromInequalities" => "coneFromHData",
 
-- Polyhedron object with associated methods:
   "Polyhedron", 
   "convexHull",
   "polyhedron",
   "polyhedronFromHData",
   "polyhedronFromInequalities" => "polyhedronFromHData",

   "facets",
   "Fan", 
   "PolyhedralComplex", 
   "intersection", 
   "fan", 
   "addCone", 
   "polyhedralComplex", 
   "addPolyhedron", 
   "ambDim", 
   "cones", 
   "maxCones", 
   "maxPolyhedra", 
   "halfspaces", 
   "hyperplanes", 
   "linSpace", 
   "linealitySpace",
   "polyhedra", 
   "vertices",
   "areCompatible", 
   "commonFace", 
   "contains", 
   "isCompact", 
   "isComplete", 
   "isEmpty", 
   "isFace", 
   "isFullDimensional",
   "isLatticePolytope", 
   "isPointed", 
   "isPolytopal", 
   "isPure",
   "isReflexive",
   "isSimplicial", 
   "isSmooth", 
   "isVeryAmple",
   "faces", 
   "facesAsPolyhedra",
   "facesAsCones",
   "fVector", 
   "incompCones",
   "incompPolyhedra",
   "inInterior", 
   "interiorPoint", 
   "interiorVector",
   "interiorLatticePoints", 
   "latticePoints", 
   "latticeVolume",
   "maxFace", 
   "minFace", 
   "objectiveVector",
   "minkSummandCone", 
   "mixedVolume", 
   "polytope", 
   "posHull" => "coneFromVData",
   "proximum", 
   "skeleton", 
   "smallestFace", 
   "smoothSubfan", 
   "stellarSubdivision", 
   "tailCone", 
   "triangulate", 
   "volume", 
   "vertexEdgeMatrix", 
   "vertexFacetMatrix", 
   "affineHull", 
   "affineImage", 
   "affinePreimage", 
   "bipyramid", 
   "ccRefinement", 
   "directProduct",
   "dualCone", 
   "faceFan", 
   "imageFan", 
   "minkowskiSum", 
   "normalFan", 
   "nVertices",
   "polar",
   "polarFace", 
   "pyramid", 
   "sublatticeBasis", 
   "toSublattice",
   "crossPolytope", 
   "cellDecompose", 
   "cyclicPolytope", 
   "ehrhart", 
   "emptyPolyhedron", 
   "hirzebruch", 
   "hypercube", 
   "newtonPolytope", 
   "posOrthant", 
   "secondaryPolytope", 
   "statePolytope", 
   "stdSimplex",
   "saveSession"}

