#ifndef __montableZZ_h
#define __montableZZ_h

using namespace std;

#include <vector>
#include <memory>
#include <algorithm>
#include <stdio.h>
#include <gmp.h>

#include "newdelete.hpp"

/* "Tricks" used in this implementation */
/* 
 1. exponent vectors: these look like: [e1, ..., en],
    where n is the number of variables.  HOWEVER, these
    exponents are never created or freed by these routines,
    so if they have more entries (e.g. a "sugar" homogenization)
    then that (those) value(s) are ignored.
 2. comparison routine: elements are kept in (increasing?) lex order.
    Is this really an OK idea?
 */

typedef int * exponents;

class MonomialTableZZ : public our_new_delete {
public:
  struct mon_term : our_new_delete {
    mon_term  *_next;
    mon_term  *_prev;
    exponents _lead;		/* Who owns this? */
    unsigned long _mask;
    int       _val;
    mpz_ptr   _coeff;           /* If not given, this is NULL */
  };

  static MonomialTableZZ *make(int nvars);
  /* Create a zero element table */

  ~MonomialTableZZ();

  void insert(mpz_t coeff, exponents exp, int comp, int id);
  /* Insert [coeff,exp,comp,id] into the table.  If there is already
     an element which is <= [exp,comp], this triple is still
     inserted.  If that is not desired, use find_divisors.
     WARNING: once 'insert' is called, insert_ZZ, find_divisors_ZZ  routines
     should not be called.
  */

  bool is_weak_member(mpz_ptr c, exponents exp, int comp) const;
  // Is [c,exp,comp] in the submodule generated by the terms in 'this'?
  // Maybe a gbvector should be returned?

  bool is_strong_member(mpz_ptr c, exponents exp, int comp) const;
  // Is [c,exp,comp] divisible by one of the terms in 'this'?

  int find_term_divisors(int max,
			 mpz_t coeff,
			 exponents exp, 
			 int comp,
			 vector<mon_term *,gc_alloc> *result = 0) const;
  /* max: the max number of divisors to find. 
     exp: the monomial whose divisors we seek.
     result: an array of mon_term's.
     return value: length of this array, i.e. the number of matches found */

  int find_monomial_divisors(int max,
			     exponents exp, 
			     int comp,
			     vector<mon_term *,gc_alloc> *result = 0) const;

  mon_term *find_exact(mpz_t coeff, exponents exp, int comp) const;
  /* If this returns non-NULL, it is valid to grab the 'val' field, and/or to assign to it.
     All other fields should be considered read only */

  static void find_weak_generators(int nvars, 
				   const vector<mpz_ptr,gc_alloc> &coeffs,
				   const vector<exponents,gc_alloc> &exps,
				   const vector<int,gc_alloc> &comps,
				   vector<int,gc_alloc> &result_positions);

  static void find_strong_generators(int nvars, 
				   const vector<mpz_ptr,gc_alloc> &coeffs,
				   const vector<exponents,gc_alloc> &exps,
				   const vector<int,gc_alloc> &comps,
				   vector<int,gc_alloc> &result_positions);

  void show(FILE *fil); /* Only for debugging */


private:
  int _nvars;
  int _count;
  vector<mon_term *,gc_alloc> _head; /* One per component */

  static mon_term *make_list_head();
};
 

#endif

// Local Variables:
// compile-command: "make -C $M2BUILDDIR/Macaulay2/e "
// End:
