import os.path
import shutil
import subprocess
Import('extractPackageName','extractPackageBaseName','getLibSpecific','setLibSpecific','untarLibrary','transferEnv',
       'configureLibrary','makeLibrary','makeInstallLibrary','deepCleanLibrary','cleanLibrary',
       'setLibSpecificStateEnvExport','setLibSpecificConfigExport','setLibSpecificMakeExport','setLibSpecificMakeInstallExport','setLibSpecificNumStages','setLibSpecificStageCommandArguments',
       'setLibSpecificStageCommand','getLibSpecificStageEnvExport','getLibSpecificConfigEnv','getLibSpecificMakeEnv','getLibSpecificMakeInstallEnv','getLibSpecificNumStages','getLibSpecificStageCommandArguments',
       'getLibSpecificStageCommand','defaultCleanLibrary','installBuilders')

#set this to library name
libraryName = 'lrslib'
#Library specific declarations go here.
setLibSpecific('all','all',libraryName,'CompressedLib','lrslib-042c.tar.gz')
setLibSpecific('all',['linux-x86','linux-x86_64','Darwin-x86_64'],libraryName,'InstallFiles',['$SConsInstallPrefixPath/lib/lrs'])
setLibSpecific('all','all',libraryName,'DecompressLib',True)
setLibSpecific('all','all',libraryName,'Dependencies',['mpir'])
setLibSpecificNumStages('all','all',libraryName,2)

setLibSpecificStageCommandArguments('all','all',libraryName,1, ['PREFIX=$SConsInstallPrefixPath','all'])
setLibSpecific('all','all',libraryName,'enableParallelSubBuild',True)
   
def BuildLibrary(target,source,env):
   """
   Build target for the library.
   """
   buildSettings = env.buildSettings
   source = source[0].rstr()
   sourceFile = os.path.split(source)[1]
   packageName = extractPackageName(sourceFile)
   cleaned = defaultCleanLibrary(buildSettings,libraryName)
   buildpath = buildSettings.getBuildPath()
   realpath = buildpath+packageName+'/'
   untarLibrary(buildSettings,source, packageName, libraryName)
   if(buildSettings.getLibSpecific(libraryName,'stage0')):
      buildSettings.setLibSpecific(libraryName,'stage1',True)
   else:
      return None
   if(makeLibrary(buildSettings,source,packageName,libraryName)):
      for target in 'lrs redund redund1 nash setupnash setupnash2 fourier buffer 2nash'.split(' '):
         shutil.copy2(realpath+target,os.path.abspath(buildSettings.getPrefixPath()+'/lib/'+target))
   return None
   
installBuilders(BuildLibrary,libraryName)
