import os.path
import shutil
import subprocess
Import('state','extractPackageName','extractPackageBaseName','getLibSpecific','setLibSpecific','getState','setState','untarLibrary','transferEnv',
       'configureLibrary','makeLibrary','makeInstallLibrary','deepCleanLibrary','cleanLibrary','architecture',
       'setLibSpecificStateEnvExport','setLibSpecificConfigExport','setLibSpecificMakeExport','setLibSpecificMakeInstallExport','setLibSpecificNumStages','setLibSpecificStageCommandArguments',
       'setLibSpecificStageCommand','getLibSpecificStageEnvExport','getLibSpecificConfigEnv','getLibSpecificMakeEnv','getLibSpecificMakeInstallEnv','getLibSpecificNumStages','getLibSpecificStageCommandArguments',
       'getLibSpecificStageCommand')

#set this to library name
libraryName = 'lapack'
#Library specific declarations go here.
setLibSpecific('all','all',libraryName,'CompressedLib','lapack-3.2.2.tgz')
setLibSpecific('all',['linux-x86','linux-x86_64'],libraryName,'InstallFiles',['$SConsInstallPrefixPath/lib/liblapack.a'])
setLibSpecific('all','all',libraryName,'DecompressLib',True)
setLibSpecificNumStages('all','all',libraryName,2)
setLibSpecificStageCommandArguments('all','all',libraryName,1, ['PREFIX=$SConsInstallPrefixPath','PLAT=','FORTRAN=gfortran','OPTS=-O2 -g','NOOPT=','LOADER=gfortran','RANLIB=ranlib','LOADOPTS=-L$SConsInstallPrefixPath/lib','TIMER=INT_ETIME','blaslib','lapack_install','lib'])
setLibSpecific('all','all',libraryName,'enableParallelSubBuild',True)
   
def BuildLibrary(target,source,env):
   """
   Build target for the library.
   """
   source = source[0].rstr()
   sourceFile = os.path.split(source)[1]
   packageName = extractPackageName(sourceFile)
   cleaned = CleanLibrary(env.mode,architecture,libraryName)
   buildpath = getState(env.mode,architecture,'buildpath')
   realpath = buildpath+packageName+'/'
   if(untarLibrary(env.state,env.mode,architecture,source, packageName, libraryName)):
      shutil.copy2(realpath+'make.inc.example',realpath+'make.inc')
   if(getLibSpecific(env.mode,architecture,libraryName,'stage0')):
      setLibSpecific(env.mode,architecture,libraryName,'stage1',True)
   else:
      return None
   if(makeLibrary(env.state,env.mode,architecture,source,packageName,libraryName)):
      for target in 'blas.a lapack.a'.split(' '):
         abstarget = os.path.abspath(getState(env.mode,architecture,'prefixpath')+'/lib/lib'+target)
         shutil.copy2(realpath+target,abstarget)
   return None
   

def CleanLibrary(mode,directory,packageBaseName):
   """
   Actual function that gets called to process a clean library command
   """
   if(deepCleanLibrary(mode,architecture,libraryName)):
      return True
   if(cleanLibrary(mode,architecture,libraryName)):
      return True   
   return False

for mode in state[architecture]['modes']:
   if(getState(mode,architecture,'build')):
      builder = Builder(action=BuildLibrary, single_source=1)
      getState(mode,architecture,'env').Append(BUILDERS = {'build_'+libraryName : builder})
      if(state[architecture][mode].get('builders')==None):
         setState(mode,architecture,'builders',{})
      getState(mode,architecture,'builders')[libraryName]=builder
