SHARED_UNITTEST_CCFILES := \
  testMain \
    M2-cpp-replacement \
    basics-test \
    fromStream \
    util-polyring-creation \
    RingElem

UNITTEST_CCFILES := \
    $(SHARED_UNITTEST_CCFILES) \
    NCGroebnerTest \
    PointArray \
    ARingZZTest \
    ARingZZGmpTest \
    ARingQQFlintTest \
    ARingQQGmpTest \
    ARingRRTest \
    ARingCCTest \
    ARingCCiTest \
    ARingRRRTest \
    ARingRRiTest \
    ARingCCCTest \
    ARingZZpTest \
    RingZZTest \
    RingZZpTest \
    RingQQTest \
    RingTowerTest \
    MatrixShape \
    DMatTest \
    ARingMatrixTest \
    MatrixTest \ 
    DMatZZpTest \
    DMatZZpFFPACKTest \
    DMatZZpFlintTest \
    DMatZZTest \
    DMatZZGMPTest \
    DMatQQGMPTest \
    DMatQQFlintTest \
    DMatRRTest \
    DMatRRRTest \
    DMatRRiTest \
    DMatCCTest \
    DMatCCCTest \
    DMatCCiTest \
    DMatGFM2Test \
    DMatGFFlintTest \
    DMatGFFlintBigTest \
    ResTest \
    SubsetTest \
    PolyRingTest \
    NewF4Test \
    ExponentVectorTest \
    ExponentListTest \
    EngineMonomialTest \
    MonomialTableTest \
    MonomialIdealTest \
    MonomialCollectionsTest \
    MonomialSortTest \
    MonomialOrderingTest \
    MonoidTest \
    MatrixIOTest \
    WeylAlgebraTest \
    QuotientRingTest \
    RingRRRTest \
    RingCCCTest \
    OverflowTest \
    BRP-test \
    RingCCCTest \
    LatticePointsTest

#    ARingGFTest \

UNITTEST_TARGET := testMain

GTEST_DIR := $(BUILTLIBPATH)/include/gtest

UNITTEST_OBJECT_FILES :=  $(addsuffix .o, $(UNITTEST_CCFILES))
UNITTEST_SHARED_OBJECT_FILES :=  $(addsuffix .o, $(SHARED_UNITTEST_CCFILES))

# Local Variables:
# compile-command: "make -C $M2BUILDDIR/Macaulay2/e/unit-tests check"
# End:
