# -*- Makefile -*-

# rules used by the Makefiles in various test directories

DOTS ?= ..
TLIMIT ?= 30
MLIMIT ?= 60000
VLIMIT ?= 60000
LIMIT  = ulimit -t $(TLIMIT) -m $(MLIMIT) -v $(VLIMIT) 2>/dev/null

RESULTS := $(notdir $(patsubst %.m2, %.out, $(wildcard $(SRCDIR)/*.m2))) \
	   $(notdir $(patsubst %.m2-input, %.out, $(wildcard $(SRCDIR)/*.m2-input)))

PAT := ':[0-9][0-9]*:[0-9][0-9]*:\([0-9][0-9]*\):|^GC'

all check :: $(RESULTS)
$(RESULTS) : $(DOTS)/bin/M2

ARGS := --silent --stop -q -e 'path=join(path,{"$(SRCDIR)/","$(SRCDIR)/$(DOTS)/packages/"})'
ARGS += --no-debug
ARGS += -e 'errorDepth=0'
# ARGS += -e 'gbTrace=5'

%.out : %.m2
	@ echo testing $<
	@ $(LIMIT); \
		if (echo 'input "$<"'; echo exit 0) | \
		   time $(DOTS)/bin/M2 $(ARGS) >$*.errors 2>&1 ; \
		then mv $*.errors $@ ; \
		else a=$$?; \
		     egrep $(PAT) <$*.errors ; \
		     echo "error: error output left in $*.errors" >&2 ; \
		     exit $$a ; \
		fi
%.out : %.m2-input
	@ echo testing $<
	@ $(LIMIT); \
		if time $(DOTS)/bin/M2 $(ARGS) <$< >$*.errors 2>&1 ; \
		then mv $*.errors $@ ; \
		else a=$$?; \
		     egrep $(PAT) <$*.errors ; \
		     echo "error: error output left in $*.errors" >&2 ; \
		     exit $$a ; \
		fi

clean::; rm -f *.okay *.out core
distclean:: clean; rm -f Makefile
