import os.path
import shutil
import subprocess
Import('extractPackageName','extractPackageBaseName','getLibSpecific','setLibSpecific','untarLibrary','transferEnv',
       'configureLibrary','makeLibrary','makeInstallLibrary','deepCleanLibrary','defaultCleanLibrary',
       'setLibSpecificStateEnvExport','setLibSpecificConfigExport','setLibSpecificMakeExport','setLibSpecificMakeInstallExport','setLibSpecificNumStages','setLibSpecificStageCommandArguments',
       'setLibSpecificStageCommand','getLibSpecificStageEnvExport','getLibSpecificConfigEnv','getLibSpecificMakeEnv','getLibSpecificMakeInstallEnv','getLibSpecificNumStages','getLibSpecificStageCommandArguments',
       'getLibSpecificStageCommand','defaultCleanLibrary','installBuilders')

#set this to library name
libraryName = 'libfac'
#Library specific declarations go here.
setLibSpecific('all','all','libfac','downloadPath','ftp://www.mathematik.uni-kl.de/pub/Math/Singular/Libfac/')
setLibSpecific('all','all',libraryName,'CompressedLib','libfac-3-1-3.tar.gz')
setLibSpecific('all',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,'InstallFiles',['$SConsInstallPrefixPath/lib/libfac.a'])
setLibSpecific('all','all',libraryName,'DecompressLib',True)
setLibSpecific('all','all',libraryName,'Dependencies',['factory'])
setLibSpecificConfigExport('all',['linux-x86','linux-x86_64','Darwin-x86'],libraryName,'CC','gcc')
setLibSpecificConfigExport('all',['linux-x86','linux-x86_64','Darwin-x86'],libraryName,'CXX','g++')
setLibSpecificMakeExport('all',['Darwin-x86_64'],libraryName,'CC','gcc -m64')
setLibSpecificMakeExport('all',['Darwin-x86_64'],libraryName,'CXX','g++ -m64')
setLibSpecificConfigExport('release',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,'CXXFLAGS','-g -O2')
setLibSpecificConfigExport('release',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,'CFLAGS','-g -O2')
setLibSpecificConfigExport('debug',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,'CXXFLAGS','-g -O0')
setLibSpecificConfigExport('debug',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,'CFLAGS','-g -O0')
setLibSpecificConfigExport('all',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,'CPPFLAGS','-I$SConsInstallPrefixPath/include/')
setLibSpecificConfigExport('all',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,'LDFLAGS','-L$SConsInstallPrefixPath/lib/')
setLibSpecificStageCommandArguments('all','all',libraryName,0,['--enable-NTL','--prefix=$SConsInstallPrefixPath'])
setLibSpecificStageCommandArguments('all','all',libraryName,1,['libfac.a'])
setLibSpecific('all','all',libraryName,'patchfile','../../../../../libraries/libfac/patch-3.1.3')
   
def BuildLibrary(target,source,env):
   """
   Build target for the library.
   """
   buildSettings = env.buildSettings
   source = source[0].rstr()
   sourceFile = os.path.split(source)[1]
   packageName = extractPackageName(sourceFile)
   cleaned = defaultCleanLibrary(buildSettings,libraryName)
   untarLibrary(buildSettings,source, packageName, libraryName)
   configureLibrary(buildSettings,source,packageName,libraryName)
   makeLibrary(buildSettings,source,packageName,libraryName)
   if(makeInstallLibrary(buildSettings,source,packageName,libraryName)):
      prefixpath = buildSettings.getPrefixPath()
      buildpath = buildSettings.getBuildPath()
      realpath = buildpath+packageName+'/'
   #install...
      shutil.copy(realpath+'libfac.a',os.path.abspath(prefixpath+'lib/libfac.a'))
   return None

installBuilders(BuildLibrary,libraryName)
