# Metadata is required: bare libraries/headers do not describe the debug ABI.
include(CMakePushCheckState)
include(CheckCXXSourceCompiles)

function(_m2_mathic_probe target header macro result)
  cmake_push_check_state(RESET)
  set(CMAKE_REQUIRED_LIBRARIES ${target})
  set(CMAKE_REQUIRED_QUIET TRUE)
  foreach(value IN ITEMS ON OFF)
    if(value)
      set(condition "ifndef")
    else()
      set(condition "ifdef")
    endif()
    unset(_m2_probe CACHE)
    check_cxx_source_compiles("#include <${header}.h>
#${condition} ${macro}
#error unexpected ABI flag
#endif
int main() { ${_m2_mathic_expression_${header}}; }" _m2_probe)
    if(_m2_probe)
      set(${result} ${value} PARENT_SCOPE)
      cmake_pop_check_state()
      return()
    endif()
  endforeach()
  set(${result} UNKNOWN PARENT_SCOPE)
  cmake_pop_check_state()
endfunction()

set(_m2_mathic_expression_memtailor "libmemtailorIsPresent()")
set(_m2_mathic_expression_mathic "libmathicIsPresent()")
set(_m2_mathic_expression_mathicgb "mgb::GroebnerConfiguration configuration(101, 2, 1)")
set(_m2_mathic_version_memtailor 1.4)
set(_m2_mathic_version_mathic 1.5)
set(_m2_mathic_version_mathicgb 1.4)
set(_m2_mathic_macro_memtailor MEMT_DEBUG)
set(_m2_mathic_macro_mathic MATHIC_DEBUG)
set(_m2_mathic_macro_mathicgb MATHICGB_DEBUG)

foreach(lib IN ITEMS memtailor mathic mathicgb)
  string(TOUPPER ${lib} upper)
  set(${upper}_PROVIDER AUTO CACHE STRING "${lib} provider: AUTO, SYSTEM, or BUNDLED")
  set_property(CACHE ${upper}_PROVIDER PROPERTY STRINGS AUTO SYSTEM BUNDLED)
  if(NOT ${upper}_PROVIDER MATCHES "^(AUTO|SYSTEM|BUNDLED)$")
    message(FATAL_ERROR "${upper}_PROVIDER must be AUTO, SYSTEM, or BUNDLED")
  endif()
  set(_${lib}_external FALSE)
  set(_${lib}_reason "requested bundled library")
  if(${upper}_PROVIDER STREQUAL "BUNDLED")
    continue()
  endif()
  set(_${lib}_target "")
  find_package(${lib} ${_m2_mathic_version_${lib}} CONFIG QUIET)
  if(TARGET ${lib}::${lib})
    set(_${lib}_target ${lib}::${lib})
    set(_${lib}_origin "CMake: ${${lib}_DIR}")
    set(_${lib}_version "${${lib}_VERSION}")
  else()
    find_package(PkgConfig QUIET)
    if(PKG_CONFIG_FOUND)
      unset(M2_${upper}_FOUND CACHE)
      pkg_check_modules(M2_${upper} QUIET IMPORTED_TARGET ${lib}>=${_m2_mathic_version_${lib}})
      if(TARGET PkgConfig::M2_${upper})
        set(_${lib}_target PkgConfig::M2_${upper})
        set(_${lib}_origin "pkg-config: ${M2_${upper}_PREFIX}")
        set(_${lib}_version "${M2_${upper}_VERSION}")
      endif()
    endif()
  endif()
  set(_${lib}_reason "no ${lib} >= ${_m2_mathic_version_${lib}} CMake or pkg-config package found")
  if(_${lib}_target)
    _m2_mathic_probe(${_${lib}_target} ${lib} ${_m2_mathic_macro_${lib}} _${lib}_debug)
    set(_${lib}_reason "installed ${lib} failed its compile/link check")
    if(NOT _${lib}_debug STREQUAL "UNKNOWN")
      set(_${lib}_external TRUE)
      message(STATUS "${lib}: detected ${_${lib}_version} (${_${lib}_origin}; ${_m2_mathic_macro_${lib}}=${_${lib}_debug})")
    endif()
  endif()
endforeach()

# Compare transitive ABI flags as well as each library's own flags. Imported
# usage requirements must describe the same dependencies M2 selected directly.
foreach(lib IN ITEMS mathic mathicgb)
  if(NOT _${lib}_external)
    continue()
  endif()
  set(dependencies memtailor)
  if(lib STREQUAL "mathicgb")
    list(APPEND dependencies mathic)
  endif()
  foreach(dep IN LISTS dependencies)
    if(NOT _${dep}_external)
      continue()
    endif()
    _m2_mathic_probe(${_${lib}_target} ${dep} ${_m2_mathic_macro_${dep}} _dependency_debug)
    if(NOT _dependency_debug STREQUAL _${dep}_debug)
      set(_${lib}_external FALSE)
      set(_${lib}_reason "its ${_m2_mathic_macro_${dep}} metadata disagrees with the selected ${dep}")
    endif()
  endforeach()
endforeach()
if(_mathicgb_external)
  _m2_mathic_probe(${_mathicgb_target} mathicgb MATHICGB_NO_TBB _mathicgb_no_tbb)
  if(_mathicgb_no_tbb STREQUAL "UNKNOWN" OR
      (WITH_TBB AND _mathicgb_no_tbb) OR
      (NOT WITH_TBB AND NOT _mathicgb_no_tbb))
    set(_mathicgb_external FALSE)
    set(_mathicgb_reason "installed MATHICGB_NO_TBB=${_mathicgb_no_tbb} disagrees with WITH_TBB=${WITH_TBB}")
  endif()
endif()

# Never link an installed library with a second, bundled copy of its dependency.
# A bundled Debug mathic/mathicgb also forces its dependencies' debug layouts.
# Propagate fallbacks to a fixed point before creating any bundled targets.
set(_selection_changed TRUE)
while(_selection_changed)
  set(_selection_changed FALSE)
  if(_mathic_external AND NOT _memtailor_external)
    set(_mathic_external FALSE)
    set(_mathic_reason "system mathic requires system memtailor")
    set(_selection_changed TRUE)
  endif()
  if(_mathicgb_external AND (NOT _mathic_external OR NOT _memtailor_external))
    set(_mathicgb_external FALSE)
    set(_mathicgb_reason "system mathicgb requires system mathic and memtailor")
    set(_selection_changed TRUE)
  endif()
  if(CMAKE_BUILD_TYPE STREQUAL "Debug" OR "Debug" IN_LIST CMAKE_CONFIGURATION_TYPES)
    if(_memtailor_external AND NOT _memtailor_debug AND
        (NOT _mathic_external OR NOT _mathicgb_external))
      set(_memtailor_external FALSE)
      set(_memtailor_reason "bundled Debug mathic/mathicgb requires MEMT_DEBUG=ON")
      set(_selection_changed TRUE)
    endif()
    if(_mathic_external AND NOT _mathic_debug AND NOT _mathicgb_external)
      set(_mathic_external FALSE)
      set(_mathic_reason "bundled Debug mathicgb requires MATHIC_DEBUG=ON")
      set(_selection_changed TRUE)
    endif()
  endif()
endwhile()

set(_bundled_mathic_targets)
foreach(lib IN ITEMS memtailor mathic mathicgb)
  string(TOUPPER ${lib} upper)
  if(_${lib}_external)
    add_library(${lib} ALIAS ${_${lib}_target})
    message(STATUS "${lib}: using system library (${_m2_mathic_macro_${lib}}=${_${lib}_debug})")
  else()
    if(${upper}_PROVIDER STREQUAL "SYSTEM")
      message(FATAL_ERROR "Cannot use system ${lib}: ${_${lib}_reason}")
    endif()
    add_subdirectory(${lib})
    # The pinned submodules set these privately. Propagate their actual layout
    # to the engine and to bundled libraries consuming a debug dependency.
    target_compile_definitions(${lib} PUBLIC $<$<CONFIG:Debug>:${_m2_mathic_macro_${lib}}>)
    list(APPEND _bundled_mathic_targets ${lib})
    message(STATUS "${lib}: bundled (${_${lib}_reason})")
  endif()
endforeach()
set(_bundled_mathic_targets "${_bundled_mathic_targets}" PARENT_SCOPE)
