--		Copyright 2004 by Daniel R. Grayson

exportMutable (
	symbol backtrace,
	symbol backupFileRegexp,
	symbol buildHomeDirectory,
	symbol compactMatrixForm,
	symbol currentFileName,
	symbol currentPackage,
	symbol currentPrompts,
	symbol debugError,
	symbol debuggerHook,
	symbol debugLevel,
	symbol debuggingMode,
	symbol encapDirectory,
	symbol errorDepth,
	symbol fileExitHooks,
	symbol fullBacktrace,
	symbol gbTrace,
	symbol globalDictionaries,
	symbol lineNumber,
	symbol loadDepth,
	symbol notify,
	symbol oo,
	symbol ooo,
	symbol oooo,
	symbol packages,
	symbol path,
	symbol prefixDirectory,
	symbol printWidth,
	symbol printingPrecision,
	symbol recursionLimit,
	symbol sourceHomeDirectory,
	symbol stopIfError
	)

export (
	symbol " ",
	symbol !,
	symbol !=,
	symbol #,
	symbol ##,
	symbol #?,
	symbol %,
	symbol &,
	symbol &&,
	symbol (,
	symbol (*),
	symbol ),
	symbol *,
	symbol **,
	symbol +,
	symbol ++,
	symbol ,,
	symbol -,
	symbol ->,
	symbol .,
	symbol ..,
	symbol .?,
	symbol /,
	symbol //,
	symbol /^,
	symbol :,
	symbol :=,
	symbol ;,
	symbol <,
	symbol <-,
	symbol <<,
	symbol <=,
	symbol <==>,
	symbol =,
	symbol =!=,
	symbol ==,
	symbol ===,
	symbol ===>,
	symbol ==>,
	symbol =>,
	symbol >,
	symbol >=,
	symbol >>,
	symbol >>>,
	symbol ?,
	symbol @,
	symbol @@,
	symbol [,
	symbol \,
	symbol \\,
	symbol ],
	symbol ^,
	symbol ^**,
	symbol ^^,
	symbol _,
	symbol {,
	symbol |,
	symbol |-,
	symbol ||,
	symbol },
	symbol ~,
	symbol abs,
	symbol accumulate,
	symbol acos,
	symbol addEndFunction,
	symbol addStartFunction,
	symbol addSynonym,
	symbol Adjacent,
	symbol adjoint,
	symbol adjoint1,				    -- adjoint' ?
	symbol Adjust,
	symbol AffineVariety,
	symbol AfterEval,
	symbol AfterNoPrint,
	symbol AfterPrint,
	symbol alarm,
	symbol Algorithm,
	symbol all,
	symbol allGenerators,
	symbol ambient,
	symbol ancestor,
	symbol ANCHOR,
	symbol and,
	symbol ann,
	symbol ann',
	symbol annihilator,
	symbol any,
	symbol append,
	symbol apply,
	symbol applyKeys,
	symbol applyPairs,
	symbol applyTable,
	symbol applyValues,
	symbol apropos,
	symbol argument,
	symbol Array,
	symbol Ascending,
	symbol ascii,
	symbol asin,
	symbol Assasinator,				    -- spelling?
	symbol assert,
	symbol assign,
	symbol Associative,
	symbol AssociativeExpression,
	symbol ass,
	symbol atan,
	symbol atEndOfFile,
	symbol autoload,
	symbol autoReduce,
	symbol Bag,
	symbol Bareiss,
	symbol baseFilename,
	symbol baseName,
	symbol baseRings,
	symbol BasicList,
	symbol basictype,
	symbol BasisElementLimit,
	symbol basis,
	symbol Bayer,
	symbol BeforePrint,
	symbol beginDocumentation,
	symbol benchmark,
	symbol betti,
	symbol between,
	symbol BIG,
	symbol BigComplex,
	symbol BigReal,
	symbol BinaryOperation,
	symbol BinaryPowerMethod,
	symbol Binomial,
	symbol binomial,
	symbol binomialCD,
	symbol BLOCKQUOTE,
	symbol BODY,
	symbol BOLD,
	symbol Boolean,
	symbol borel,
	symbol boxList,
	symbol boxTable,
	symbol BR,
	symbol break,
	symbol briefDocumentation,
	symbol browse,
	symbol buckets,
	symbol CacheTable,
	symbol cache,
	symbol CallLimit,
	symbol capture,
	symbol Caveat,
	symbol CC,
	symbol ceiling,
	symbol centerString,
	symbol ChainComplex,
	symbol ChainComplexMap,
	symbol chainComplex,
	symbol ChangeMatrix,
	symbol char,
	symbol characters,
	symbol CHECKED,
	symbol check,
	symbol checkShadow,
	symbol CITE,
	symbol class,
	symbol clearAll,
	symbol clearEcho,
	symbol clearOutput,
	symbol close,
	symbol closeIn,
	symbol closeOut,
	symbol closePackage,
	symbol CODE,
	symbol code,
	symbol CodimensionLimit,
	symbol codim,
	symbol coefficientRing,
	symbol coefficients,
	symbol Cofactor,
	symbol CoherentSheaf,
	symbol cohomology,
	symbol coimage,
	symbol cokernel,
	"coker" => symbol cokernel,
	symbol collectGarbage,
	symbol columnate,
	symbol combine,
	symbol Command,
	symbol commandInterpreter,
	symbol commandLine,
	symbol complement,
	symbol CompleteIntersection,
	symbol complete,
	symbol Component,
	symbol components,
	symbol compress,
	symbol concatenate,
	symbol conductor,
	symbol cone,
	symbol conjugate,
	symbol connectionCount,
	symbol Consequences,
	symbol content,
	symbol continue,
	symbol contract,
	symbol contract',
	symbol ConvertApply,
	symbol ConvertJoin,
	symbol ConvertRepeat,
	symbol copy,
	symbol copyDirectory,
	symbol copyFile,
	symbol copyright,
	symbol cos,
	symbol cosh,
	symbol cotangentSheaf,
	symbol cover,
	symbol coverMap,
	symbol currentDirectory,
	symbol currentFileDirectory,
	symbol Database,
	symbol dd,
	symbol debugDoc,
	symbol DebuggingMode,
	symbol decompose,
	symbol deepSplice,
	symbol Degree,
	symbol degreeLength,
	symbol DegreeLimit,
	symbol DegreeMap,
	symbol DegreeOrder,
	symbol Degrees,
	symbol degree,
	symbol degrees,
	symbol degreesMonoid,
	symbol degreesRing,
	symbol delete,
	symbol demark,
	symbol denominator,
	symbol depth,
	symbol Descending,
	symbol describe,
	symbol Description,
	symbol det,
	symbol DFN,
	symbol Dictionary,
	symbol dictionary,
	symbol diff,
	symbol diff',
	symbol difference,
	symbol dillyDally,
	symbol dim,
	symbol directSum,
	symbol disassemble,
	symbol DistributedMarkUpType,
	symbol DIV,
	symbol Divide,
	symbol divideByVariable,
	symbol DL,
	symbol DocumentTag,
	symbol do,
	symbol document,
	symbol documentation,
	symbol DoubleArrow,
	symbol Down,
	symbol DownArrow,
	symbol drop,
	symbol dual,
	symbol dumpdata,
	symbol echoOff,
	symbol echoOn,
	symbol edit,
	symbol EHV,					    -- cryptic
	symbol EHVprimaryDecomposition,			    -- cryptic
	symbol elements,
	symbol Eliminate,
	symbol Elimination,
	symbol EliminationOrder,
	symbol else,
	symbol EM,					    -- cryptic
	symbol EmptyMarkUpType,
	symbol Encapsulate,
	symbol End,
	symbol end,
	symbol endl,
	symbol Engine,
	symbol EngineRing,
	symbol Entity,
	symbol entries,
	symbol environment,
	symbol Equation,
	symbol erase,
	symbol error,
	symbol errorCode,
	symbol errorReport,
	symbol euler,
	symbol evaluate,
	symbol even,
	symbol examine,
	symbol EXAMPLE,
	symbol Examples,
	symbol examples,
	symbol ExampleTABLE,
	symbol Exclude,
	symbol exec,
	symbol exit,
	symbol exp,
	symbol expandWord,
	symbol exponents,
	symbol export,
	symbol exportMutable,
	symbol Expression,
	symbol expression,
	symbol Ext,
	symbol extend,
	symbol exteriorPower,
	symbol extract,
	symbol factor,
	symbol false,
	symbol Fano,
	symbol fastgb,
	symbol fastquotient,
	symbol fetchRawDocumentation,
	symbol File,
	symbol fileChangeMode,
	symbol fileDictionaries,
	symbol fileExists,
	symbol fileMode,
	symbol FileName,
	symbol FilePosition,
	symbol fileTime,
	symbol findFiles,
	symbol findNonMember,
	symbol FindOne,
	symbol findSynonyms,
	symbol First,
	symbol first,
	symbol firstkey,
	symbol fittingIdeal,
	symbol flagLookup,
	symbol flatten,
	symbol flattener,
	symbol flip,
	symbol floor,
	symbol flush,
	symbol fold,
	symbol ForestNode,
	symbol Format,
	symbol FormattedKey,
	symbol for,
	symbol forceGB,
	symbol fork,
	symbol format,
	symbol formatDocumentTag,
	symbol FractionField,
	symbol frac,
	symbol fraction,
	symbol frame,
	symbol frames,
	symbol from,
	symbol fromDual,
	symbol fromFilename,
	symbol Function,
	symbol FunctionApplication,
	symbol GaloisField,
	symbol GBDegrees,
	symbol gb,
	symbol gcd,
	symbol gcdCoefficients,
	symbol GeneralOrderedMonoid,
	symbol genera,
	symbol generatorExpressions,
	symbol generators,
	"gens" => symbol generators,
	symbol generatorsTable,
	symbol generatorSymbols,
	symbol genericMatrix,
	symbol genericSkewMatrix,
	symbol genericSymmetricMatrix,
	symbol genus,
	symbol get,
	symbol getChangeMatrix,
	symbol getc,
	symbol getenv,
	symbol getGlobalSymbol,
	symbol getMatrix,
	symbol getNonUnit,
	symbol getParsing,
	symbol getWWW,
	symbol getZeroDivisor,
	symbol GF,
	-- symbol ggConcatBlocks,
	-- symbol ggPush,
	-- symbol gg;,
	-- symbol ggautoreduce;,
	-- symbol ggbetti;,
	-- symbol ggborel;,
	-- symbol ggcalc;,
	-- symbol ggcoeffs;,
	-- symbol ggcompare;,
	-- symbol ggcopy;,
	-- symbol ggdeclarefield;,
	-- symbol ggdets;,
	-- symbol ggdim;,
	-- symbol ggdiv;,
	-- symbol ggdup;,
	-- symbol ggelem;,
	-- symbol ggelim;,
	-- symbol ggexterior;,
	-- symbol ggexteriorproduct;,
	-- symbol ggfactor1;,
	-- symbol ggfactor2;,
	-- symbol gggb;,
	-- symbol gggcdextended;,
	-- symbol gggetchange;,
	-- symbol gggetcols;,
	-- symbol gggetgb;,
	-- symbol gggetmingens;,
	-- symbol gggetsyz;,
	-- symbol gggetvalue;,
	-- symbol gggetzerodivisor;,
	-- symbol ggGF;,
	-- symbol gghilb;,
	-- symbol ggindex;,
	-- symbol gginitial;,
	-- symbol ggINT;,
	-- symbol ggisequal;,
	-- symbol ggissubset;,
	-- symbol ggkbasis;,
	-- symbol ggleadmonom;,
	-- symbol ggmatrix;,
	-- symbol ggmodtensor;,
	-- symbol ggmonideal;,
	-- symbol ggmult;,
	-- symbol ggnegate;,
	-- symbol ggnmonoms;,
	-- symbol ggpairs;,
	-- symbol ggpfaffs;,
	-- symbol ggpick;,
	-- symbol ggpop;,
	-- symbol ggprimes;,
	-- symbol ggqring;,
	-- symbol ggrandom;,
	-- symbol ggrandomseed;,
	-- symbol ggreduce;,
	-- symbol ggremaining;,
	-- symbol ggres;,
	-- symbol ggresmap;,
	-- symbol ggresmodule;,
	-- symbol ggringmap;,
	-- symbol ggsat;,
	-- symbol ggsimplify;,
	-- symbol ggsortcolumns;,
	-- symbol ggstats;,
	-- symbol ggsubmatrix;,
	-- symbol ggterm;,
	-- symbol ggtonet;,
	-- symbol ggtruncate;,
	-- symbol callgg;,
	-- symbol convert;,
	-- symbol ConvertToExpression;,
	-- symbol eePopBool;,
	-- symbol eePopInt;,
	-- symbol eePopIntarray;,
	-- symbol handle;,
	symbol GLex,
	symbol global,
	symbol globalAssignFunction,
	symbol GlobalAssignHook,
	symbol globalAssignment,
	symbol globalAssignmentHooks,
	symbol globalReleaseFunction,
	symbol GlobalReleaseHook,
	symbol GradedModule,
	symbol GradedModuleMap,
	symbol gradedModule,
	symbol gradedModuleMap,
	symbol graphIdeal,
	symbol graphRing,
	symbol Grassmannian,
	symbol GRevLex,
	symbol GRevLexSmall,
	symbol GRevLexTiny,
	symbol GroebnerBasis,
	symbol GroupLex,
	symbol HardDegreeLimit,
	symbol HashTable,
	symbol hash,
	symbol hashTable,
	symbol HEAD,
	symbol HEADER1,
	symbol HEADER2,
	symbol HEADER3,
	symbol HEADER4,
	symbol HEADER5,
	symbol HEADER6,
	symbol HeaderType,
	symbol Headline,
	symbol headline,
	symbol height,
	symbol help,
	symbol HH,
	symbol Hilbert,
	symbol hilbertFunction,
	symbol hilbertFunctionRing,
	symbol hilbertPolynomial,
	symbol hilbertSeries,
	symbol history,
	symbol Holder,
	symbol hold,
	symbol Hom,
	symbol Homogeneous,
	symbol homogenize,
	symbol homology,
	symbol homomorphism,
	symbol horizontalJoin,
	symbol HprimaryDecomposition,
	symbol HR,
	symbol HREF,
	symbol HTML,
	symbol html,
	symbol htmlDebug,
	symbol htmlDefaults,
	symbol htmlExtraLiteral,
	symbol htmlFilename,
	symbol htmlLiteral,
	symbol Hybrid,
	symbol Hypertext,
	symbol hypertext,
	symbol ICfractions,
	symbol ICfractionsLong,
	symbol ICmap,
	symbol ICnode,
	symbol Ideal,
	symbol id,
	symbol ideal,
	symbol identity,
	symbol if,
	symbol IgnoreExampleErrors,
	symbol ii,
	symbol image,
	symbol imaginaryPart,
	symbol IMG,
	symbol ImmutableType,
	symbol Increment,
	symbol in,
	symbol incomparable,
	symbol independentSets,
	symbol IndeterminateNumber,
	symbol indeterminate,
	symbol IndexedVariable,
	symbol index,
	symbol indexComponents,
	symbol indices,
	symbol inducedMap,
	symbol inducesWellDefinedMap,
	symbol InfiniteNumber,
	symbol infinity,
	symbol InfoDirSection,
	symbol info,
	symbol infoHelp,
	symbol infoTagConvert,
	symbol Inhomogeneous,
	symbol InputContinuationPrompt,
	symbol InputPrompt,
	symbol Inputs,
	symbol input,
	symbol installAssignmentMethod,
	symbol installMethod,
	symbol installPackage,
	symbol instance,
	symbol integralClosure,
	symbol integrate,
	symbol interpreterDepth,
	symbol intersect,
	symbol InverseMethod,
	symbol Inverses,
	symbol irreducibleCharacteristicSeries,
	symbol isAbsoluteExecPath,
	symbol isAbsolutePath,
	symbol isAffineRing,
	symbol isBorel,
	symbol isCommutative,
	symbol isConstant,
	symbol isDirectory,
	symbol isDirectSum,
	symbol isField,
	symbol isFreeModule,
	symbol isGlobalSymbol,
	symbol isHomogeneous,
	symbol isIdeal,
	symbol isInjective,
	symbol isInputFile,
	symbol isIsomorphism,
	symbol isListener,
	symbol isModule,
	symbol isMonomialIdeal,
	symbol isNormal,
	symbol isOpen,
	symbol isOutputFile,
	symbol isPolynomialRing,
	symbol isPrime,
	symbol isPrimitive,
	symbol isQuotientModule,
	symbol isQuotientOf,
	symbol isQuotientRing,
	symbol isReady,
	symbol isRegularFile,
	symbol isRing,
	symbol isSquareFree,
	symbol isSubmodule,
	symbol isSubset,
	symbol isSurjective,
	symbol isTable,
	symbol isUnit,
	symbol isWellDefined,
	symbol ITALIC,
	symbol Iterate,
	symbol jacobian,
	symbol join,
	symbol KBD,
	symbol kernel,
	"ker" => symbol kernel,
	symbol Key,
	symbol keys,
	symbol Keyword,
	symbol kill,
	symbol koszul,
	symbol LABEL,
	symbol last,
	symbol LAYOUT,
	symbol leadCoefficient,
	symbol leadComponent,
	symbol leadMonomial,
	symbol leadTerm,
	symbol LengthLimit,
	symbol length,
	symbol Lex,
	symbol LexSmall,
	symbol LexTiny,
	symbol lift,
	symbol liftable,
	symbol Limit,
	symbol Linear,
	symbol lines,
	symbol link,
	symbol listForm,
	symbol LISTING,
	symbol List,
	symbol list,
	symbol listLocalSymbols,
	symbol listSymbols,
	symbol listUserSymbols,
	symbol LITERAL,
	symbol LMatrixCC,
	symbol LMatrixRR,
	symbol load,
	symbol loaddata,
	symbol loadPackage,
	symbol local,
	symbol localDictionaries,
	symbol localize,
	symbol localSymbols,
	symbol locate,
	symbol log,
	symbol LongPolynomial,
	symbol lookup,
	symbol lookupCount,
	symbol LowerBound,
	-- symbol M2CC,					    -- ?
	symbol makeDirectory,
	symbol makeDocumentTag,
	symbol MakeInfo,
	symbol makeMonomialOrdering,
	symbol makePackageIndex,
	symbol Manipulator,
	symbol map,
	symbol MarkUpList,
	symbol MarkUpListParagraph,
	symbol MarkUpType,
	symbol match,
	symbol matches,
	symbol mathML,
	symbol Matrix,
	symbol MatrixExpression,
	symbol matrix,
	symbol max,
	symbol maximumCodeWidth,
	symbol maxPosition,
	symbol member,
	symbol memoize,
	symbol MENU,
	symbol merge,
	symbol mergePairs,
	symbol method,
	symbol methodDispatchFunctions,
	symbol methodFunctionOptions,
	symbol methodOptions,
	symbol methods,
	symbol mingens,
	symbol mingle,
	symbol MinimalGenerators,
	symbol MinimalMatrix,
	symbol MinorsComputation,
	symbol min,
	symbol minimizeFilename,
	symbol minors,
	symbol minPosition,
	symbol minPres,
	symbol minPresIdeal,
	symbol minPresMap,
	symbol minPresMapIdeal,
	symbol minPresMapInv,
	symbol minprimes,
	symbol minSat,
	symbol minSatPPD,
	symbol minSatPPDold,
	symbol Minus,
	symbol minus,
	symbol mkdir,
	symbol modifyRing,
	symbol Module,
	symbol ModuleMap,
	symbol mod,
	symbol module,
	symbol modulo,
	symbol Monoid,
	symbol MonoidElement,
	symbol monoid,
	symbol Monomial,
	symbol monomialCurve,
	symbol monomialCurveIdeal,
	symbol MonomialIdeal,
	symbol monomialIdeal,
	symbol MonomialOrder,
	symbol MonomialSize,
	symbol Monomials,
	symbol monomialSubideal,
	symbol moveFile,
	symbol MutableHashTable,
	symbol MutableList,
	symbol mutable,
	symbol Name,
	symbol name,
	symbol NCLex,
	symbol needs,
	symbol needsPackage,
	symbol Net,
	symbol net,
	symbol netRows,
	symbol new,
	symbol newClass,
	symbol newCoordinateSystem,
	symbol newdecompose,
	symbol NewFromMethod,
	symbol newHandle,
	symbol newline,
	symbol NewMethod,
	symbol newModule,
	symbol NewOfFromMethod,
	symbol NewOfMethod,
	symbol newPackage,
	symbol nextkey,
	symbol NL,
	symbol NOINDENT,
	symbol NonAssociativeProduct,
	symbol NonLinear,
	symbol nonUnit,
	symbol NoPrint,
	symbol noPrompts,
	symbol normalPrompts,
	symbol NOTCHECKED,
	symbol Nothing,
	symbol not,
	symbol notImplemented,
	symbol null,
	symbol nullaryMethods,
	symbol nullhomotopy,
	symbol number,
	symbol numerator,
	symbol Numeric,
	symbol numeric,
	symbol numgens,
	symbol odd,
	symbol OFCLASS,
	symbol of,
	symbol OL,
	symbol oldCoefficients,
	symbol OldSynopsis,
	symbol OneExpression,
	symbol on,
	symbol OO,
	symbol openDatabase,
	symbol openDatabaseOut,
	symbol openFiles,
	symbol openIn,
	symbol openInOut,
	symbol openListener,
	symbol openOut,
	symbol operatorNames,
	symbol Option,
	symbol Options,
	symbol options,
	symbol OptionTable,
	symbol Order,
	symbol OrderedMonoid,
	symbol or,
	symbol order,
	symbol OutputDictionary,
	symbol Outputs,
	symbol override,
	symbol Package,
	symbol PackageDictionary,
	symbol pack,
	symbol package,
	symbol packageTag,
	symbol pad,
	symbol pager,
	symbol PairLimit,
	symbol PairsRemaining,
	symbol pairs,
	symbol PARA,
	symbol PARA1,
	symbol ParagraphList,
	symbol parent,
	symbol partitions,
	symbol PDC,
	symbol PDdonode,
	symbol pdim,
	symbol PDinitialize,
	symbol PDnext,
	symbol peek,
	symbol peek',
	symbol pfaffians,
	symbol pi,
	symbol plus,
	symbol poincare,
	symbol poincareComputation,
	symbol poincareN,
	symbol PolynomialRing,
	symbol pop,
	symbol popDictionary,
	symbol Position,
	symbol position,
	symbol positions,
	symbol Power,
	symbol power,
	symbol PPD,
	symbol PPDcharSets,
	symbol PPDSpecialCharSets,
	symbol PRE,
	symbol precedence,
	symbol precision,
	symbol Prefix,
	symbol prepend,
	symbol presentation,
	symbol Primary,
	symbol primaryComponent,
	symbol primaryDecomposition,
	symbol primdecComputation,
	symbol PrimitiveElement,
	symbol Print,
	symbol print,
	symbol printExamples,
	symbol printingTimeLimit,
	symbol PrintLevel,
	symbol PrintNames,
	symbol printString,
	symbol processID,
	symbol Product,
	symbol ProductOrder,
	symbol product,
	symbol profile,
	symbol profileSummary,
	symbol Proj,
	symbol Projective,
	symbol ProjectiveHilbertPolynomial,
	symbol projectiveHilbertPolynomial,
	symbol ProjectiveVariety,
	symbol promote,
	symbol promptWidth,
	symbol protect,
	symbol prune,
	symbol pruningMap,
	symbol Pseudocode,
	symbol pseudocode,
	symbol pseudoRemainder,
	symbol pushDictionary,
	symbol PushforwardComputation,
	symbol pushForward,
	symbol pushForward1,
	symbol QQ,
	symbol quit,
	symbol quote,
	symbol QuotientRing,
	symbol quotient,
	symbol quotMin,
	symbol quotMinold,
	symbol radical,
	symbol radicalContainment,
	symbol random,
	symbol rank,
	-- symbol raw,
	-- symbol rawAmbientRing,
	-- symbol rawAssociatedPrimes,
	-- symbol rawBigCC,
	-- symbol rawBigRR,
	-- symbol rawCC,
	-- symbol rawCharSeries,
	-- symbol rawCodimension,
	-- symbol rawCoefficient,
	-- symbol rawCoefficients,
	-- symbol rawColon,
	-- symbol rawColumnChange,
	-- symbol rawCompareMonomial,
	-- symbol RawComputation,
	-- symbol rawConcat,
	-- symbol rawConcatBlocks,
	-- symbol rawConcatColumns,
	-- symbol rawConcatRows,
	-- symbol rawDeclareField,
	-- symbol rawDegree,
	-- symbol rawDeleteColumns,
	-- symbol rawDeleteRows,
	-- symbol rawDenominator,
	-- symbol rawDenominatorRing,
	-- symbol rawDirectSum,
	-- symbol rawDivideByVariable,
	-- symbol rawDivMod,
	-- symbol rawDual,
	-- symbol rawEigenvalues,
	-- symbol rawEigenvaluesHermitian,
	-- symbol rawEigenvaluesSymmetric,
	-- symbol rawEigenvectors,
	-- symbol rawEigenvectorsHermitian,
	-- symbol rawEigenvectorsSymmetric,
	-- symbol rawEliminateVariables,
	-- symbol rawExteriorPower,
	-- symbol rawFactor,
	-- symbol rawFlip,
	-- symbol rawFraction,
	-- symbol rawFractionRing,
	-- symbol RawFreeModule,
	-- symbol rawFreeModule,
	-- symbol rawFromNumber,
	-- symbol rawGB,
	-- symbol rawGBBetti,
	-- symbol rawGBChangeOfBasis,
	-- symbol rawGBContains,
	-- symbol rawGBForce,
	-- symbol rawGBGetLeadTerms,
	-- symbol rawGBGetMatrix,
	-- symbol rawGBMatrixLift,
	-- symbol rawGBMatrixRemainder,
	-- symbol rawGBMinimalGenerators,
	-- symbol rawGBSetHilbertFunction,
	-- symbol rawGBSetStop,
	-- symbol rawGBSyzygies,
	-- symbol rawGCD,
	-- symbol rawGetEpsilonMatrixCC,
	-- symbol rawGetEpsilonMatrixRR,
	-- symbol rawGetMatrixEntryCC,
	-- symbol rawGetMatrixEntryRR,
	-- symbol rawGetSchreyer,
	-- symbol rawGetSubmatrix,
	-- symbol rawGetTerms,
	-- symbol rawGetZeroDivisor,
	-- symbol rawHilbert,
	-- symbol rawHomogenize,
	-- symbol rawIdealReorder,
	-- symbol rawIdentity,
	-- symbol rawIndexIfVariable,
	-- symbol rawIndices,
	-- symbol rawInitial,
	-- symbol rawInsertColumns,
	-- symbol rawInsertRows,
	-- symbol rawIntersect,
	-- symbol rawIsDense,
	-- symbol rawIsEqual,
	-- symbol rawIsField,
	-- symbol rawIsHomogeneous,
	-- symbol rawIsMutable,
	-- symbol rawIsStronglyStable,
	-- symbol rawIsZero,
	-- symbol rawKeepVariables,
	-- symbol rawKoszul,
	-- symbol rawKoszulMonomials,
	-- symbol rawLCM,
	-- symbol rawLeadCoefficient,
	-- symbol rawLeadMonomial,
	-- symbol rawLeastSquares,
	-- symbol rawLeastSquaresDeficient,
	-- symbol rawLift,
	-- symbol rawLocalRing,
	-- symbol rawLU,
	-- symbol rawMakeMonomial,
	-- symbol RawMatrix,
	-- symbol rawMatrix1,
	-- symbol rawMatrix2,
	-- symbol rawMatrixCC,
	-- symbol rawMatrixColumnChange,
	-- symbol rawMatrixColumnOperation2,
	-- symbol rawMatrixColumnScale,
	-- symbol rawMatrixColumnSwap,
	-- symbol rawMatrixContract,
	-- symbol rawMatrixDiff,
	-- symbol rawMatrixEntry,
	-- symbol rawMatrixRandom,
	-- symbol rawMatrixRemake1,
	-- symbol rawMatrixRemake2,
	-- symbol rawMatrixRowChange,
	-- symbol rawMatrixRowOperation2,
	-- symbol rawMatrixRowScale,
	-- symbol rawMatrixRowSwap,
	-- symbol rawMatrixRR,
	-- symbol rawMinors,
	-- symbol RawMonoid,
	-- symbol rawMonoid,
	-- symbol RawMonomial,
	-- symbol RawMonomialIdeal,
	-- symbol rawMonomialIdeal,
	-- symbol rawMonomialIdealToMatrix,
	-- symbol RawMonomialOrdering,
	-- symbol rawMonomialOrdering,
	-- symbol rawMonomials,
	-- symbol rawMultiDegree,
	-- symbol rawNumberOfColumns,
	-- symbol rawNumberOfColumnsCC,
	-- symbol rawNumberOfColumnsRR,
	-- symbol rawNumberOfInvertibleVariables,
	-- symbol rawNumberOfRows,
	-- symbol rawNumberOfRowsCC,
	-- symbol rawNumberOfRowsRR,
	-- symbol rawNumberOfVariables,
	-- symbol rawNumerator,
	-- symbol rawNumgens,
	-- symbol RawObject,
	-- symbol rawPairs,
	-- symbol rawPermuteColumns,
	-- symbol rawPermuteRows,
	-- symbol rawPfaffians,
	-- symbol rawPolynomialRing,
	-- symbol rawProductMonomialOrdering,
	-- symbol rawPromote,
	-- symbol rawPseudoRemainder,
	-- symbol rawQQ,
	-- symbol rawQuotientRing,
	-- symbol rawRadical,
	-- symbol rawRank,
	-- symbol rawReshape,
	-- symbol rawResolution,
	-- symbol rawResolutionGetFree,
	-- symbol rawResolutionGetMatrix,
	-- symbol rawResolutionStatusLevel,
	-- symbol RawRing,
	-- symbol RawRingElement,
	-- symbol RawRingMap,
	-- symbol rawRing,
	-- symbol rawRingMap,
	-- symbol rawRingMapEval,
	-- symbol rawRingVar,
	-- symbol rawRowChange,
	-- symbol rawRR,
	-- symbol rawSaturate,
	-- symbol rawSchurRing,
	-- symbol rawSetEpsilonMatrixCC,
	-- symbol rawSetEpsilonMatrixRR,
	-- symbol rawSetMatrixEntryCC,
	-- symbol rawSetMatrixEntryRR,
	-- symbol rawSetMatrixValues,
	-- symbol rawSkewPolynomialRing,
	-- symbol rawSolvableAlgebra,
	-- symbol rawSolve,
	-- symbol rawSortColumns,
	-- symbol rawSortColumns2,
	-- symbol rawSource,
	-- symbol rawSparseListFormMonomial,
	-- symbol rawSparseMatrix1,
	-- symbol rawSparseMatrix2,
	-- symbol rawStartComputation,
	-- symbol rawStatus1,
	-- symbol rawStatus2,
	-- symbol RawStatusCodes,
	-- symbol rawStatusResolution,
	-- symbol rawStronglyStableClosure,
	-- symbol rawSubmatrix,
	-- symbol rawSubmodule,
	-- symbol rawSVD,
	-- symbol rawSymmetricPower,
	-- symbol rawSyzygy,
	-- symbol rawTarget,
	-- symbol rawTensor,
	-- symbol rawTerm,
	-- symbol rawTermCount,
	-- symbol rawToInteger,
	-- symbol rawVarMonomial,
	-- symbol rawWeylAlgebra,
	-- symbol rawZero,
	-- symbol rawZZ,
	-- symbol rawZZp,
	symbol read,
	symbol readDirectory,
	symbol readlink,
	symbol realPart,
	symbol realpath,
	symbol recursionDepth,
	symbol regularity,
	symbol relations,
	symbol relativizeFilename,
	symbol relativizeFilename2,
	symbol remove,
	symbol removeDirectory,
	symbol removeFile,
	symbol removeLowestDimension,
	symbol removePackage,
	symbol reorganize,
	symbol Repair,
	symbol replaceContents,
	symbol reshape,
	symbol Resolution,
	symbol resolution,
	"res" => symbol resolution,
	symbol restart,
	symbol return,
	symbol returnCode,
	symbol ReverseDictionary,
	symbol reverse,
	symbol RevLex,
	symbol RightArrow,
	symbol Ring,
	symbol RingElement,
	symbol RingMap,
	symbol ring,
	symbol rotate,
	symbol RowExpression,
	symbol RR,
	symbol rsort,
	symbol run,
	symbol runEndFunctions,
	symbol runLengthEncoding,
	symbol runStartFunctions,
	symbol same,
	symbol sameFunctionBody,
	symbol SAMP,
	symbol saturate,
	symbol scan,
	symbol scanKeys,
	symbol scanPairs,
	symbol scanValues,
	symbol Schur,
	symbol SchurRing,
	symbol ScriptedFunctor,
	symbol SeeAlso,
	symbol seeParsing,
	symbol select,
	symbol selectInSubring,
	symbol selectLargest,
	symbol selectRegexp,
	symbol SelfInitializingType,
	symbol sendgg,
	symbol separate,
	symbol separateExampleOutput,
	symbol separateM2output,
	symbol separateRegexp,
	symbol SEQ,
	symbol Sequence,
	symbol seq,
	symbol sequence,
	symbol Set,
	symbol set,
	symbol setEcho,
	symbol setPrecision,
	symbol setRandomSeed,
	symbol sheaf,
	symbol sheafExt,
	symbol sheafHom,
	symbol SheafOfRings,
	symbol shield,
	symbol showHtml,
	symbol showStructure,
	symbol showTex,
	symbol showUserStructure,
	symbol silentRobustNetWithClass,
	symbol silentRobustString,
	symbol silentRobustStringWithClass,
	symbol SimplePowerMethod,
	symbol SingleArgumentDispatch,
	symbol sin,
	symbol singleton,
	symbol singularLocus,
	symbol sinh,
	symbol size,
	symbol SkewCommutative,
	symbol sleep,
	symbol SMALL,
	symbol someTerms,
	symbol somethingElse,
	symbol Sort,
	symbol sort,
	symbol sortByDegree,
	symbol sortColumns,
	symbol SortStrategy,
	symbol source,
	symbol SparseMonomialVectorExpression,
	symbol SparseVectorExpression,
	symbol Spec,
	symbol splice,
	symbol sqrt,
	symbol stack,
	symbol standardForm,
	symbol standardPairs,
	symbol startupString1,
	symbol startupString2,
	symbol stats,
	symbol status,
	symbol stderr,
	symbol stdio,
	symbol StopBeforeComputation,
	symbol StopWithMinimalGenerators,
	symbol Strategy,
	symbol String,
	symbol STRONG,
	symbol SUB,
	symbol submatrix,
	symbol submodule,
	symbol Subnodes,
	symbol subquotient,
	symbol SubringLimit,
	symbol Subscript,
	symbol subscript,
	symbol SUBSECTION,
	symbol subsets,
	symbol substitute,
	"sub" => symbol substitute,
	symbol substring,
	symbol subtable,
	symbol Sum,
	symbol SumOfTwists,
	symbol sum,
	symbol summary,
	symbol SUP,
	symbol Superscript,
	symbol super,
	symbol superscript,
	symbol SY,
	symbol Symbol,
	symbol symbol,
	symbol symmetricAlgebra,
	symbol symmetricPower,
	symbol synonym,
	symbol SYprimaryDecomposition,
	symbol Syzygies,
	symbol SyzygyLimit,
	symbol SyzygyMatrix,
	symbol SyzygyRows,
	symbol syz,
	symbol syzygyScheme,
	symbol TABLE,
	symbol Table,
	symbol table,
	symbol take,
	symbol Tally,
	symbol tally,
	symbol tan,
	symbol tangentSheaf,
	symbol tanh,
	symbol target,
	symbol temporaryFileName,
	symbol tensor,
	symbol tensorAssociativity,
	symbol terms,
	symbol TEST,
	symbol testDebugging,
	symbol TEX,
	symbol texLiteral,
	symbol TeXmacsBegin,
	symbol TeXmacsEnd,
	symbol TeXmacsEvaluate,
	symbol tex,
	symbol texMath,
	symbol then,
	symbol Thing,
	symbol Time,
	symbol time,
	symbol times,
	symbol timing,
	symbol TITLE,
	symbol Title,
	symbol TO,
	symbol TO2,
	symbol to,
	symbol toBigReal,
	symbol toDual,
	symbol toExternalString,
	symbol toField,
	symbol toFilename,
	symbol TOH,
	symbol toList,
	symbol toLower,
	symbol top,
	symbol topCoefficients,
	symbol topicList,
	symbol topics,
	symbol topLevelTexmacs,
	symbol TopNodeName,
	symbol Tor,
	symbol toSequence,
	symbol toString,
	symbol TotalPairs,
	symbol toUpper,
	symbol trace,
	symbol transpose,
	symbol TreeNode,
	symbol trim,
	symbol true,
	symbol truncate,
	symbol truncateOutput,
	symbol try,
	symbol TT,
	symbol Type,
	symbol TypicalValue,
	symbol typicalValues,
	symbol UL,
	symbol ultimate,
	symbol unbag,
	symbol UNDERLINE,
	symbol undocumented,
	symbol unhex,
	symbol uniform,
	symbol unique,
	symbol unlink,
	symbol unlist,
	symbol Unmixed,
	symbol unSingleton,
	symbol unstack,
	symbol Up,
	symbol Usage,
	symbol UseHilbertFunction,
	symbol UserDictionary,
	symbol use,
	symbol userSymbols,
	symbol Using,
	symbol value,
	symbol values,
	symbol VAR,
	symbol Variable,
	symbol VariableBaseName,
	symbol VariableOrder,
	symbol Variables,
	symbol variables,
	symbol Variety,
	symbol variety,
	symbol vars,
	symbol varsR2,
	symbol Vector,
	symbol vector,
	symbol Verbose,
	symbol Verify,
	symbol Version,
	symbol version,
	symbol verticalJoin,
	symbol VerticalList,
	symbol VisibleList,
	symbol wait,
	symbol wedgeProduct,
	symbol Weights,
	symbol WeylAlgebra,
	symbol when,
	symbol while,
	symbol width,
	symbol Wrap,
	symbol WrapperType,
	symbol wrap,
	symbol XMP,
	symbol xor,
	symbol youngest,
	symbol ZeroExpression,
	symbol zero,
	symbol ZZ
)

-- Local Variables:
-- compile-command: "make -C $M2BUILDDIR/Macaulay2/m2 "
-- End:
