document { "translating programs from Macaulay",
     "Macaulay 2 aims to provide all of the functionality of Macaulay, but
     the names of the functions are not the same, and there are
     other differences.  One major difference is the introduction of the
     notion of module, whereas in Macaulay, the pervasive concept was
     the matrix.",
     PARA,
     "Here is a list of old Macaulay functions, together with pointers to
     functions in Macaulay 2 that might be used to replace them.",
     PARA,
     MENU {
	  ("Macaulay commands:",
	  MENU {
	       SHIELD (". -- not available"),
	       SHIELD ("ac -- such destructive changes are not allowed"),
	       SHIELD ("add -- ", TO "+"),
	       SHIELD ("ar -- ", TO "not documented yet"),
	       SHIELD ("args -- ", TO "not documented yet"),
	       SHIELD ("betti -- ", TO "betti"),
	       SHIELD ("binoms -- ", TO "not documented yet"),
	       SHIELD ("cache_mem -- ", TO "not documented yet"),
	       SHIELD ("calc -- ", TO "not documented yet"),
	       SHIELD ("cat -- ", TO "not documented yet"),
	       SHIELD ("cdir -- ", TO "not documented yet"),
	       SHIELD ("ce -- ", TO "not documented yet"),
	       SHIELD ("characteristic -- ", TO "char"),
	       SHIELD ("chcalc -- ", TO "not documented yet"),
	       SHIELD ("codim -- ", TO "codim"),
	       SHIELD ("coef -- ", TO "not documented yet"),
	       SHIELD ("col_degree -- ", TO "not documented yet"),
	       SHIELD ("col_degs -- ", TO "not documented yet"),
	       SHIELD ("commands -- ", TO "not documented yet"),
	       SHIELD ("compress -- ", TO "compress"),
	       SHIELD ("concat -- ", TO "|", ",", TO "||"),
	       SHIELD ("continue -- ", TO "not documented yet"),
	       SHIELD ("contract -- ", TO "contract"),
	       SHIELD ("copy -- ", TO "not documented yet"),
	       SHIELD ("degree -- ", TO "degree"),
	       SHIELD ("determinants -- ", TO "minors"),
	       SHIELD ("diag -- ", TO "not documented yet"),
	       SHIELD ("diff -- ", TO "diff"),
	       SHIELD ("dshift -- ", TO "not documented yet"),
	       SHIELD ("dsum -- ", TO "++"),
	       SHIELD ("echo -- ", TO "not documented yet"),
	       SHIELD ("edit -- ", TO "not documented yet"),
	       SHIELD ("edit_map -- ", TO "not documented yet"),
	       SHIELD ("elim -- ", TO "selectInSubring"),
	       SHIELD ("endmon -- ", TO "not documented yet"),
	       SHIELD ("ev -- ", TO "substitute", ",", TO "RingMap"),
	       SHIELD ("exit -- ", TO "quit"),
	       SHIELD ("fetch -- ", TO "substitute"),
	       SHIELD ("flatten -- ", TO "flatten"),
	       SHIELD ("forcestd -- ", TO "forceGB"),
	       SHIELD ("help -- ", TO "help"),
	       SHIELD ("help_file -- ", TO "not documented yet"),
	       SHIELD ("hilb -- ", TO "hilbertSeries", ",",TO "hilbertPolynomial",
		    ",",TO "hilbertFunction", ",",TO "poincare"),
	       SHIELD ("hilb_numer -- ", TO "hilbertSeries"),
	       SHIELD ("homog -- ", TO "homogenize"),
	       SHIELD ("hulb -- ", TO "not documented yet"),
	       SHIELD ("ideal -- ", TO "ideal", ", ", TO "matrix"),
	       SHIELD ("iden -- ", TO "id"),
	       SHIELD ("if -- ", TO "if"),
	       SHIELD ("imap -- ", TO "map"),
	       SHIELD ("in -- ", TO "leadTerm"),
	       SHIELD ("incoef -- ", TO "not documented yet"),
	       SHIELD ("incr_set -- ", TO "not documented yet"),
	       SHIELD ("inpart -- ", TO "not documented yet"),
	       SHIELD ("int -- ", TO "not documented yet"),
	       SHIELD ("intersect -- ", TO "intersect"),
	       SHIELD ("is_zero -- ", TO "=="),
	       SHIELD ("jacob -- ", TO "jacobian"),
	       SHIELD ("jump -- ", TO "not documented yet"),
	       SHIELD ("k-basis -- ", TO "basis"),
	       SHIELD ("k_basis -- ", TO "basis"),
	       SHIELD ("keep -- ", TO "not documented yet"),
	       SHIELD ("kill -- ", TO "not documented yet"),
	       SHIELD ("koszul -- ", TO "koszul"),
	       SHIELD ("lift -- ", TO "//"),
	       SHIELD ("lift_std -- ", TO "gb"),
	       SHIELD ("listvars -- ", TO "listUserSymbols"),
	       SHIELD ("mat -- ", TO "matrix"),
	       SHIELD ("max -- ", TO "max"),
	       SHIELD ("mc -- ", TO "not documented yet"),
	       SHIELD ("min -- ", TO "min"),
	       SHIELD ("modulo -- ", TO "modulo"),
	       SHIELD ("monitor -- ", TO "emacs"),
	       SHIELD ("monitoring -- ", TO "not documented yet"),
	       SHIELD ("monoms -- ", TO "not documented yet"),
	       SHIELD ("monprimes -- ", TO "not documented yet"),
	       SHIELD ("mr -- ", TO "not documented yet"),
	       SHIELD ("mult -- ", TO "*"),
	       SHIELD ("ncols -- ", "use numgens source m"),
	       SHIELD ("nres -- ", TO "resolution"),
	       SHIELD ("nrows -- ", "use numgens target m"),
	       SHIELD ("numinfo -- ", TO "not documented yet"),
	       SHIELD ("nvars -- ", "use numgens R"),
	       SHIELD ("outer -- ", TO "**"),
	       SHIELD ("path -- ", TO "path"),
	       SHIELD ("pc -- ", TO "not documented yet"),
	       SHIELD ("pfaff -- ", TO "pfaffians"),
	       SHIELD ("pmap -- ", TO "not documented yet"),
	       SHIELD ("poly -- ", TO "not documented yet"),
	       SHIELD ("power -- ", TO "^"),
	       SHIELD ("pr -- ", TO "not documented yet"),
	       SHIELD ("pres -- ", TO "not documented yet"),
	       SHIELD ("present_ring -- ", TO "not documented yet"),
	       SHIELD ("pring -- ", TO "not documented yet"),
	       SHIELD ("prmat -- ", TO "print", " or ", TO "name"),
	       SHIELD ("putchange -- ", TO "not documented yet"),
	       SHIELD ("putmat -- ", TO "not documented yet"),
	       SHIELD ("putstd -- ", TO "not documented yet"),
	       SHIELD ("qring -- ", TO "not documented yet"),
	       SHIELD ("quit -- ", TO "not documented yet"),
	       SHIELD ("quotient -- ", TO "not documented yet"),
	       SHIELD ("random -- ", TO "not documented yet"),
	       SHIELD ("reduce -- ", TO "not documented yet"),
	       SHIELD ("res -- ", TO "not documented yet"),
	       SHIELD ("reset -- ", TO "not documented yet"),
	       SHIELD ("ring -- ", TO "not documented yet"),
	       SHIELD ("ring-from-rows -- ", TO "not documented yet"),
	       SHIELD ("ring_from_cols -- ", TO "not documented yet"),
	       SHIELD ("ring_from_rows -- ", TO "not documented yet"),
	       SHIELD ("ring_sum -- ", TO "not documented yet"),
	       SHIELD ("rings -- ", TO "not documented yet"),
	       SHIELD ("rmap -- ", TO "not documented yet"),
	       SHIELD ("row_degree -- ", TO "not documented yet"),
	       SHIELD ("row_degs -- ", TO "not documented yet"),
	       SHIELD ("sat -- ", TO "saturate"),
	       SHIELD ("set -- ", TO "not documented yet"),
	       SHIELD ("set_value -- ", TO "not documented yet"),
	       SHIELD ("setcoldegs -- ", TO "not documented yet"),
	       SHIELD ("setdegs -- ", TO "not documented yet"),
	       SHIELD ("setring -- ", TO "not documented yet"),
	       SHIELD ("shout -- ", TO "not documented yet"),
	       SHIELD ("size -- ", TO "not documented yet"),
	       SHIELD ("smult -- ", TO "*"),
	       SHIELD ("space -- ", TO "engineMemory"),
	       SHIELD ("spairs -- ", TO "not documented yet"),
	       SHIELD ("spare -- ", TO "not documented yet"),
	       SHIELD ("sparse -- ", TO "not documented yet"),
	       SHIELD ("standard -- ", TO "gb"),
	       SHIELD ("std -- ", TO "not documented yet"),
	       SHIELD ("std_minimal -- ", TO "not documented yet"),
	       SHIELD ("stdpart -- ", TO "not documented yet"),
	       SHIELD ("sub -- ", TO "not documented yet"),
	       SHIELD ("submat -- ", TO "submatrix"),
	       SHIELD ("subtract -- ", TO "-"),
	       SHIELD ("syz -- ", TO "syz", ",", TO "kernel"),
	       SHIELD ("tensor -- ", TO "not documented yet"),
	       SHIELD ("to-ring -- ", TO "not documented yet"),
	       SHIELD ("tr -- ", TO "not documented yet"),
	       SHIELD ("trace -- ", TO "trace"),
	       SHIELD ("transpose -- ", TO "transpose"),
	       SHIELD ("truncate -- ", TO "truncate"),
	       SHIELD ("type -- ", TO "not documented yet"),
	       SHIELD ("version -- ", TO "version"),
	       SHIELD ("wedge -- ", TO "minors", ",", TO "exteriorPower")
	       }),
	  ("Macaulay scripts from 'scriptsde':",
	  MENU {
	       SHIELD ("<adj_of_cat -- ", TO "not documented yet"),
	       SHIELD ("<adjoin_fractions -- ", TO "not documented yet"),
	       SHIELD ("<adjoint -- ", TO "not documented yet"),
	       SHIELD ("<analytic_spread -- ", TO "not documented yet"),
	       SHIELD ("<annihilated -- ", TO "not documented yet"),
	       SHIELD ("<annihilator -- ", TO "ann"),
	       SHIELD ("<annihilator1 -- ", TO "ann"),
	       SHIELD ("<annihilator2 -- ", TO "ann"),
	       SHIELD ("<binomial -- ", TO "binomial"),
	       SHIELD ("<ceiling -- ", TO "not documented yet"),
	       SHIELD ("<changelog -- ", TO "not documented yet"),
	       SHIELD ("<codim -- ", TO "not documented yet"),
	       SHIELD ("<cohomology -- ", TO "not documented yet"),
	       SHIELD ("<cohomology1 -- ", TO "not documented yet"),
	       SHIELD ("<column_vector -- ", TO "not documented yet"),
	       SHIELD ("<complement -- ", TO "not documented yet"),
	       SHIELD ("<copyring -- ", TO "not documented yet"),
	       SHIELD ("<cotan -- ", TO "not documented yet"),
	       SHIELD ("<cotan_bihom -- ", TO "not documented yet"),
	       SHIELD ("<curve_on_cubic -- ", TO "not documented yet"),
	       SHIELD ("<diagonal_submodule -- ", TO "not documented yet"),
	       SHIELD ("<diff -- ", TO "not documented yet"),
	       SHIELD ("<double_dual -- ", TO "not documented yet"),
	       SHIELD ("<double_dual1 -- ", TO "not documented yet"),
	       SHIELD ("<dual_variety -- ", TO "not documented yet"),
	       SHIELD ("<empty_array -- ", TO "not documented yet"),
	       SHIELD ("<equality -- ", TO "not documented yet"),
	       SHIELD ("<ext -- ", TO "not documented yet"),
	       SHIELD ("<ext(-,r) -- ", TO "not documented yet"),
	       SHIELD ("<extend_ring -- ", TO "not documented yet"),
	       SHIELD ("<from_bigraded -- ", TO "not documented yet"),
	       SHIELD ("<from_div_powers -- ", TO "not documented yet"),
	       SHIELD ("<generic_mat -- ", TO "genericMatrix"),
	       SHIELD ("<getvars -- ", TO "not documented yet"),
	       SHIELD ("<hom -- ", TO "not documented yet"),
	       SHIELD ("<hom_and_map -- ", TO "not documented yet"),
	       SHIELD ("<hom_is_0 -- ", TO "not documented yet"),
	       SHIELD ("<homology -- ", TO "not documented yet"),
	       SHIELD ("<i_in_j -- ", TO "not documented yet"),
	       SHIELD ("<ideal -- ", TO "not documented yet"),
	       SHIELD ("<idempotent -- ", TO "not documented yet"),
	       SHIELD ("<idencoldegs -- ", TO "not documented yet"),
	       SHIELD ("<idenrowdegs -- ", TO "not documented yet"),
	       SHIELD ("<interchange -- ", TO "not documented yet"),
	       SHIELD ("<interchange_permutation -- ", TO "not documented yet"),
	       SHIELD ("<inverse -- ", TO "not documented yet"),
	       SHIELD ("<is_zero -- ", TO "not documented yet"),
	       SHIELD ("<k3carpet -- ", TO "not documented yet"),
	       SHIELD ("<kernel -- ", TO "not documented yet"),
	       SHIELD ("<kernel_and_map -- ", TO "not documented yet"),
	       SHIELD ("<kosz_hom1 -- ", TO "not documented yet"),
	       SHIELD ("<kosz_hom2 -- ", TO "not documented yet"),
	       SHIELD ("<l_i_in_j -- ", TO "not documented yet"),
	       SHIELD ("<l_intersect -- ", TO "not documented yet"),
	       SHIELD ("<l_res -- ", TO "not documented yet"),
	       SHIELD ("<lex_seg_ideal -- ", TO "not documented yet"),
	       SHIELD ("<macaulayrep -- ", TO "not documented yet"),
	       SHIELD ("<map_from_col -- ", TO "not documented yet"),
	       SHIELD ("<minpres -- ", TO "not documented yet"),
	       SHIELD ("<module_iso -- ", TO "not documented yet"),
	       SHIELD ("<monomial_curve -- ", TO "not documented yet"),
	       SHIELD ("<mult_ideals -- ", TO "not documented yet"),
	       SHIELD ("<nbyn_commuting -- ", TO "not documented yet"),
	       SHIELD ("<normal_sheaf -- ", TO "not documented yet"),
	       SHIELD ("<nres -- ", TO "not documented yet"),
	       SHIELD ("<nzd -- ", TO "not documented yet"),
	       SHIELD ("<orbit_equations -- ", TO "not documented yet"),
	       SHIELD ("<permutation -- ", TO "not documented yet"),
	       SHIELD ("<perp -- ", TO "not documented yet"),
	       SHIELD ("<points -- ", TO "not documented yet"),
	       SHIELD ("<powers -- ", TO "not documented yet"),
	       SHIELD ("<project_from_product -- ", TO "not documented yet"),
	       SHIELD ("<projective_plane -- ", TO "not documented yet"),
	       SHIELD ("<prune -- ", TO "prune"),
	       SHIELD ("<prune_and_map -- ", TO "not documented yet"),
	       SHIELD ("<push_forward -- ", TO "pushForward"),
	       SHIELD ("<push_forward1 -- ", TO "pushForward1"),
	       SHIELD ("<quotient1 -- ", TO "quotient"),
	       SHIELD ("<radical -- ", TO "radical"),
	       SHIELD ("<random_element -- ", TO "not documented yet"),
	       SHIELD ("<random_int -- ", TO "not documented yet"),
	       SHIELD ("<random_map -- ", TO "not documented yet"),
	       SHIELD ("<random_mat -- ", TO "not documented yet"),
	       SHIELD ("<rank_prob -- ", TO "not documented yet"),
	       SHIELD ("<rat_nor_curve -- ", TO "not documented yet"),
	       SHIELD ("<rat_nor_osc_locus -- ", TO "not documented yet"),
	       SHIELD ("<rational_surface -- ", TO "not documented yet"),
	       SHIELD ("<rational_surface1 -- ", TO "not documented yet"),
	       SHIELD ("<reduce_syzygy_1 -- ", TO "not documented yet"),
	       SHIELD ("<regular_sequence -- ", TO "not documented yet"),
	       SHIELD ("<regular_sequence1 -- ", TO "not documented yet"),
	       SHIELD ("<regularity -- ", TO "regularity"),
	       SHIELD ("<remove_low_dim -- ", TO "not documented yet"),
	       SHIELD ("<remove_low_dim_id -- ", TO "not documented yet"),
	       SHIELD ("<remove_lowest_dim -- ", TO "not documented yet"),
	       SHIELD ("<representatives -- ", TO "not documented yet"),
	       SHIELD ("<representatives_old -- ", TO "not documented yet"),
	       SHIELD ("<res -- ", TO "resolution"),
	       SHIELD ("<res_and_dim -- ", TO "resolution", ",", TO "pdim"),
	       SHIELD ("<ring -- ", TO "not documented yet"),
	       SHIELD ("<sagbi -- ", TO "not documented yet"),
	       SHIELD ("<sagbi_step -- ", TO "not documented yet"),
	       SHIELD ("<sat -- ", TO "saturate"),
	       SHIELD ("<sat1 -- ", TO "saturate"),
	       SHIELD ("<scroll -- ", TO "not documented yet"),
	       SHIELD ("<select -- ", TO "not documented yet"),
	       SHIELD ("<shout_list -- ", TO "not documented yet"),
	       SHIELD ("<sort_by_degree -- ", TO "not documented yet"),
	       SHIELD ("<stack -- ", TO "matrix", ",",TO "map"),
	       SHIELD ("<submat_by_degs -- ", TO "not documented yet"),
	       SHIELD ("<subring -- ", TO "kernel"),
	       SHIELD ("<sym -- ", TO "not documented yet"),
	       SHIELD ("<sym_cokernel -- ", TO "not documented yet"),
	       SHIELD ("<template_for_scripts -- ", TO "not documented yet"),
	       SHIELD ("<to_div_powers -- ", TO "not documented yet"),
	       SHIELD ("<tor -- ", TO "Tor"),
	       SHIELD ("<unmixed_radical -- ", TO "radical"),
	       SHIELD ("<unmixed_radical1 -- ", TO "radical"),
	       SHIELD ("<unmixed_radical2 -- ", TO "radical"),
	       SHIELD ("<wedge_cokernel -- ", TO "not documented yet"),
	       SHIELD ("<x_to_last -- ", TO "newCoordinateSystem"),
	       SHIELD ("<zeromat -- ", TO "not documented yet")
	       }),
	  ("Macaulay scripts from 'scriptsmj':",
	  MENU {
	       SHIELD ("<2BYN -- ", TO "not documented yet"),
	       SHIELD ("<add_matrix_to_array -- ", TO "not documented yet"),
	       SHIELD ("<check_complex -- ", TO "not documented yet"),
	       SHIELD ("<check_exact -- ", TO "not documented yet"),
	       SHIELD ("<comp_to_array -- ", TO "not documented yet"),
	       SHIELD ("<eagon_northcott -- ", TO "not documented yet"),
	       SHIELD ("<extract_matrix -- ", TO "not documented yet"),
	       SHIELD ("<homology_of_array -- ", TO "not documented yet"),
	       SHIELD ("<jordan0 -- ", TO "not documented yet"),
	       SHIELD ("<koszul_complex -- ", TO "not documented yet"),
	       SHIELD ("<lift -- ", TO "not documented yet"),
	       SHIELD ("<lift_arrays -- ", TO "not documented yet"),
	       SHIELD ("<mc -- ", TO "not documented yet"),
	       SHIELD ("<nilpotent0 -- ", TO "not documented yet"),
	       SHIELD ("<pres -- ", TO "not documented yet"),
	       SHIELD ("<smult_complex -- ", TO "not documented yet"),
	       SHIELD ("<splice_resns -- ", TO "not documented yet")
	       }),
	  ("Macaulay scripts from 'scriptsms':",
	  MENU {
	       SHIELD ("<block_map -- ", TO "not documented yet"),
	       SHIELD ("<blowup -- ", TO "not documented yet"),
	       SHIELD ("<blowup0 -- ", TO "not documented yet"),
	       SHIELD ("<generic_skew_mat -- ", TO "genericSkewMatrix"),
	       SHIELD ("<generic_sym_mat -- ", TO "genericSymmetricMatrix"),
	       SHIELD ("<hilb_fcn -- ", TO "not documented yet"),
	       SHIELD ("<inhomog_std -- ", TO "not documented yet"),
	       SHIELD ("<l_dual0 -- ", TO "not documented yet"),
	       SHIELD ("<l_from_dual -- ", TO "fromDual"),
	       SHIELD ("<l_homog0 -- ", TO "not documented yet"),
	       SHIELD ("<l_min0 -- ", TO "not documented yet"),
	       SHIELD ("<l_minimal -- ", TO "not documented yet"),
	       SHIELD ("<l_minimal0 -- ", TO "not documented yet"),
	       SHIELD ("<l_tangentcone -- ", TO "not documented yet"),
	       SHIELD ("<l_to_dual -- ", TO "toDual"),
	       SHIELD ("<line_bundle_image -- ", TO "not documented yet"),
	       SHIELD ("<normal_cone -- ", TO "not documented yet"),
	       SHIELD ("<proj_bundle -- ", TO "not documented yet"),
	       SHIELD ("<rmap -- ", TO "not documented yet"),
	       SHIELD ("<symmetric_algebra -- ", TO "not documented yet")
	       })
	  }
     }

document { "not documented yet", 
     "We haven't documented yet the way to replace this Macaulay function or
     script."
     }
