# -*- Mode: Makefile -*-
# @configure_input@

include ../../../../include/config.Makefile

.PHONY : all

ARGS := -q '-epath=join(path,{"../../","$(srcdir)/"})' '-eerrorDepth(0)' --silent

all :: ../../../$(DUMPDATAFILE)

else
ifeq "$(CC)" "cl"
## work around weirdness in the Microsoft runtime startup - it eliminates backslashes
## and does strange things to quotation marks.
ARGS := -q --silent '-epath=join(path,{\"../../\",\"$(srcdir)/\"})' '-eerrorDepth(0)'
else
ARGS := -q --silent \
		'-e path=join({"../../../m2/","$(srcdir)/../m2/","$(srcdir)/../packages/"})' \
		'-e errorDepth(0)'
endif
endif


%.okay : %.m2
	@ echo testing $<
	@ env M2HOME=@srcdir@/.. ../../../bin/Macaulay2 $(ARGS) $< '-eexit(0)'
	@ touch $@

TESTFILES := $(wildcard *.m2)
TESTRESULTS := $(patsubst %.m2, %.okay, $(TESTFILES))

all:: $(TESTRESULTS)

ifneq "$(DUMPDATA)" "no"
$(TESTRESULTS) : ../../../$(DUMPDATAFILE)
else
$(TESTRESULTS) : ../../../cache/Macaulay2-doc
endif
