--		Copyright 1997-2002 by Daniel R. Grayson

sendgg = X -> error "'sendgg' has been removed"
ggPush = X -> error "'ggPush' has been removed"
ConvertJoin = X -> error "'ConvertJoin' has been removed"
ConvertRepeat = X -> error "'ConvertRepeat' has been removed"
ConvertApply = X -> error "'ConvertApply' has been removed"

unlist = X -> error "'unlist' has been replaced by toSequence"
elements = X -> error "'elements' has been replace by toList"
expand = X -> error "'expand' has been replaced by 'value'"
evaluate = X -> error "'evaluate' has been replaced by 'value'"
seq = X -> error "'seq' has been replaced by 'singleton'"
verticalJoin = X -> error "'verticalJoin' has been replaced by 'stack'"
-- name = X -> error "'name' has been replaced by 'toString'"
quote = X -> error "'quote' has been replaced by 'symbol'"
Numeric = X -> error "'Numeric' has been replaced by 'numeric'"
submodule = X -> error "'submodule' has been removed"
stats = X -> error "'stats' has been replaced by 'summary'"
monomialCurve = X -> error "'monomialCurve' has been replaced by 'monomialCurveIdeal'"
