undocumented {
    (net, LITERAL),
    (net, LATER),
    (expression, Constant),
    (expression, RealField),
    (expression, ComplexField),
    (expression, PolynomialRing),
    (expression, ProjectiveHilbertPolynomial),
    (expression, Module),
    (expression, Matrix),
    (expression, SheafOfRings),
    (expression, GeneralOrderedMonoid),
    (expression, Eliminate),
    (expression, FractionField),
    (expression, CoherentSheaf),
    (expression, Expression),
    (expression, VisibleList),
    (expression, Ideal),
    (expression, IndexedVariableTable),
    (expression, ZZ),
    (expression, RingMap),
    (expression, QQ),
    (expression, RR),
    (expression, CC),
    (expression, IndexedVariable),
    (expression, MonomialIdeal),
    (expression,Boolean),
    (expression,EngineRing),
    (expression,Function),
    (expression,GaloisField),
    (expression,MutableMatrix),
    (expression,Option),
    (expression,QuotientRing),
    (expression,ScriptedFunctor),
    (expression,Set),
    (expression,Type),
    (expression,Variety),
    (expression,Vector),
    (html, Hypertext),
    (html, COMMENT),
    (html, CDATA),
--    (html, Holder2),
    (html, Holder),
    (html, Nothing),
    (html, LATER),
    (html, PRE),
    (html, IMG),
    (html, HTML),
    (html, LITERAL),
    (html, HREF),
    (html, TO2),
    (html, TO),
    (html, TOH),
    (html, MENU),
    (html, String),
    (html, RowExpression),
    (html, Boolean),
    (html, Descent),
    (html, Function),
    (html, Net),
    (html, Ring),
    (html, RingFamily),
    (html, Thing),
    (html, Type),
    (info, LITERAL),
    (info, Hypertext),
    (info, SUB),
    (info, SUP),
    (info, TT),
    (info, Nothing),
    (info, HR),
    (info, CODE),
    (info, HREF),
    (info, TABLE),
    (info, PRE),
    (info, TITLE),
    (info, UL),
    (info, COMMENT),
    (info, HypertextContainer),
    (info, IMG),
    (info, TO2),
    (info, TO),
    (info, HEADER1),
    (info, TOH),
    (info, HEADER2),
    (info, LATER),
    (info, HEADER3),
    (info, MENU),
    (info, String)
    }

undocumented {
    (hold, Expression),(hold, Thing),
    (symbol +, Sum, ZeroExpression),
    (symbol +, Holder, ZeroExpression),
    (symbol +, Sum, Sum),
    (symbol +, Holder, Sum),
    (symbol +, ZeroExpression, Expression),
    (symbol +, Expression, ZeroExpression),
    (symbol +, Expression, Sum),
    (symbol +, Sum, Expression),
    (expression, Thing),
    (expression, Symbol),
    symbol (,
    symbol ),
    symbol [,
    symbol ],
    symbol {,
    symbol }
    }

-- Local Variables:
-- compile-command: "make -C $M2BUILDDIR/Macaulay2/m2 "
-- End:
