F4_CCFILES := ntuple_monomial varpower_monomial moninfo \
        montable monhashtable monsort \
        F4 F4types F4computation F4toM2interface gausser
# memblock.cpp is included in F4.cpp.
# F4spairs 
F4_CFILES := 
F4_FILES := $(F4_CCFILES) $(F4_CFILES)
F4_OBJECT_FILES :=  $(addsuffix .o, $(F4_FILES))
