import os.path
import shutil
import subprocess
Import('extractPackageName','extractPackageBaseName','getLibSpecific','setLibSpecific','untarLibrary','transferEnv',
       'configureLibrary','makeLibrary','makeInstallLibrary','deepCleanLibrary','cleanLibrary',
       'setLibSpecificStateEnvExport','setLibSpecificConfigExport','setLibSpecificMakeExport','setLibSpecificMakeInstallExport','setLibSpecificNumStages','setLibSpecificStageCommandArguments',
       'setLibSpecificStageCommand','getLibSpecificStageEnvExport','getLibSpecificConfigEnv','getLibSpecificMakeEnv','getLibSpecificMakeInstallEnv','getLibSpecificNumStages','getLibSpecificStageCommandArguments',
       'getLibSpecificStageCommand','defaultCleanLibrary','installBuilders')

#set this to library name
libraryName = 'nauty'
#Library specific declarations go here.
setLibSpecific('all','all',libraryName,'CompressedLib','nauty24r2.tar.gz')
setLibSpecific('all',['linux-x86','linux-x86_64','Darwin-x86_64'],libraryName,'InstallFiles',['$SConsInstallPrefixPath/bin/listg'])
setLibSpecific('all','all',libraryName,'DecompressLib',True)
setLibSpecific('all','all',libraryName,'Dependencies',['mpir'])

setLibSpecificConfigExport('all',['linux-x86','linux-x86_64'],libraryName,'CC','gcc')
setLibSpecificConfigExport('all',['linux-x86','linux-x86_64'],libraryName,'CXX','g++')
setLibSpecificConfigExport('all',['Darwin-x86_64'],libraryName,'CC','gcc -m64')
setLibSpecificConfigExport('all',['Darwin-x86_64'],libraryName,'CXX','g++ -m64')
setLibSpecificConfigExport('all',['linux-x86','linux-x86_64','Darwin-x86_64'],libraryName,'CPPFLAGS','-I$SConsInstallPrefixPath/include/')
setLibSpecificConfigExport('all',['linux-x86','linux-x86_64','Darwin-x86_64'],libraryName,'LDFLAGS','-L$SConsInstallPrefixPath/lib/')
setLibSpecificStageCommandArguments('all','all',libraryName,0,['--disable-shared','--prefix=$SConsInstallPrefixPath'])
setLibSpecificStageCommandArguments('all','all',libraryName,1,['all'])
setLibSpecificNumStages('all','all',libraryName,2)
setLibSpecific('all','all',libraryName,'enableParallelSubBuild',True)
   
def BuildLibrary(target,source,env):
   """
   Build target for the library.
   """
   source = source[0].rstr()
   sourceFile = os.path.split(source)[1]
   packageName = extractPackageName(sourceFile)
   buildSettings = env.buildSettings
   cleaned = defaultCleanLibrary(buildSettings,libraryName)
   untarLibrary(buildSettings,source, packageName, libraryName)
   configureLibrary(buildSettings,source,packageName,libraryName)
   if makeLibrary(buildSettings,source,packageName,libraryName):
      buildpath = buildSettings.getBuildPath()
      realpath = buildpath+packageName+'/'
      try:
         os.makedirs(os.path.abspath(buildSettings.getPrefixPath()+'/bin'))
      except:
         None
      for target in 'NRswitchg addedgeg amtog biplabg catg complg copyg countg deledgeg directg dreadnaut dretog genbg geng genrang gentourng labelg listg multig newedgeg pickg planarg shortg showg'.split(' '):
         shutil.copy2(realpath+target,os.path.abspath(buildSettings.getPrefixPath()+'/bin/'+target))
   return None
   
installBuilders(BuildLibrary,libraryName)
