Import('setLibSpecific',
       'setLibSpecificStateEnvExport','setLibSpecificConfigExport','setLibSpecificMakeExport','setLibSpecificMakeInstallExport','setLibSpecificNumStages','setLibSpecificStageCommandArguments',
       'setLibSpecificStageCommand','buildBuilders')

#set this to library name
libraryName = 'gc'
#Library specific declarations go here.
setLibSpecific('all','all',libraryName,'CompressedLib','gc-7.2alpha7-2011-07-25.tar.gz')
setLibSpecific('all',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,'InstallFiles',['$SConsInstallPrefixPath/lib/libgc.a'])
setLibSpecific('all','all',libraryName,'DecompressLib',True)
setLibSpecific('all','all',libraryName,'allowsystem',True)
setLibSpecific('all','all',libraryName,'systemlibs',['gc','atomic_ops',])
setLibSpecific('all','all',libraryName,'systemcincludes',['gc.h','atomic_ops.h'])
setLibSpecific('all','all',libraryName,'systemcppincludes',['gc_cpp.h'])
setLibSpecific('all','all',libraryName,'tarfolder','gc-7.2alpha7')
setLibSpecificNumStages('all','all',libraryName,6)

setLibSpecificConfigExport('release',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,'CFLAGS','-g -O2')
setLibSpecificConfigExport('debug',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,'CFLAGS','-g -O0')
setLibSpecificConfigExport('all',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,'CPPFLAGS','-I$SConsInstallPrefixPath/include/')
setLibSpecificConfigExport('all',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,'LDFLAGS','-L$SConsInstallPrefixPath/lib/')
setLibSpecificConfigExport('all',['linux-x86','linux-x86_64','Darwin-x86'],libraryName,'CC','gcc')
setLibSpecificConfigExport('all',['linux-x86','linux-x86_64','Darwin-x86'],libraryName,'CXX','g++')
setLibSpecificConfigExport('all',['Darwin-x86_64'],libraryName,'CC','gcc -m64')
setLibSpecificConfigExport('all',['Darwin-x86_64'],libraryName,'CXX','g++ -m64')
setLibSpecificStageCommandArguments('all',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,0,['--enable-threads=posix','--enable-parallel-mark','--disable-shared','--enable-large-config','--disable-gcj-support','--disable-java-finalization', '--prefix=$SConsInstallPrefixPath'])

setLibSpecificStateEnvExport('release',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,3,'CFLAGS','-g -O2')
setLibSpecificStateEnvExport('debug',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,3,'CFLAGS','-g -O0')
setLibSpecificStateEnvExport('all',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,3,'CPPFLAGS','-I$SConsInstallPrefixPath/include/')
setLibSpecificStateEnvExport('all',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,3,'LDFLAGS','-L$SConsInstallPrefixPath/lib/')
setLibSpecificStateEnvExport('all',['linux-x86','linux-x86_64','Darwin-x86'],libraryName,3,'CC','gcc')
setLibSpecificStateEnvExport('all',['linux-x86','linux-x86_64','Darwin-x86'],libraryName,3,'CXX','g++')
setLibSpecificStateEnvExport('all',['Darwin-x86_64'],libraryName,3,'CC','gcc')
setLibSpecificStateEnvExport('all',['Darwin-x86_64'],libraryName,3,'CXX','g++')
setLibSpecificStageCommandArguments('all',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,3,['--prefix=$SConsInstallPrefixPath'])
setLibSpecificStageCommandArguments('all',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,5,['install'])
setLibSpecificStageCommand('all',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,3,'configure')
setLibSpecificStageCommand('all',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,4,'make')
setLibSpecificStageCommand('all',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,5,'make')
setLibSpecific('all',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,'stage3DirOffset','libatomic_ops/')
setLibSpecific('all',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,'stage4DirOffset','libatomic_ops/')
setLibSpecific('all',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,'stage5DirOffset','libatomic_ops/')

buildBuilders(libraryName)
