regex("d", "1abcddddeF2")
regex("d*", "1abcddddeF2")
regex("d+", "1abcddddeF2")
regex("d+", "1abceF2")
regex("cdd+e", "1abcddddeF2")
regex("cd(d+)e", "1abcddddeF2")
regex("[a-z]+", "1abcddddeF2")
regex("[[:alpha:]]+", "Dog cat cat.")
regex("([[:alpha:]]+) *\\1","Dog cat cat.")
