assert Equation(RObject 5 + RObject 2, RObject 7)
assert Equation(RObject 5 + 2, RObject 7)
assert Equation(5 + RObject 2, RObject 7)
assert Equation(RObject 5 - RObject 2, RObject 3)
assert Equation(RObject 5 - 2, RObject 3)
assert Equation(5 - RObject 2, RObject 3)
assert Equation(RObject 5 * RObject 2, RObject 10)
assert Equation(RObject 5 * 2, RObject 10)
assert Equation(5 * RObject 2, RObject 10)
assert Equation(RObject 5 / RObject 2, RObject 2.5)
assert Equation(RObject 5 / 2, RObject 2.5)
assert Equation(5 / RObject 2, RObject 2.5)
assert Equation(RObject 5^(RObject 2), RObject 25)
assert Equation(RObject 5^2, RObject 25)
assert Equation(5^(RObject 2), RObject 25)
assert Equation(RObject 5 % RObject 2, RObject 1)
assert Equation(RObject 5 % 2, RObject 1)
assert Equation(5 % RObject 2, RObject 1)
assert Equation(RObject 5 // RObject 2, RObject 2)
assert Equation(RObject 5 // 2, RObject 2)
assert Equation(5 // RObject 2, RObject 2)
assert Equation(RObject 5 ?? RObject 2, RObject 5)
assert Equation(RObject null ?? RObject 2, RObject 2)
