assert Equation(RObject 2, RObject 2)
assert Equation(RObject 2, 2)
assert Equation(2, RObject 2)
assert BinaryOperation(symbol <, RObject 2, RObject 3)
assert BinaryOperation(symbol <, RObject 2, 3)
assert BinaryOperation(symbol <, 2, RObject 3)
assert BinaryOperation(symbol <=, RObject 2, RObject 3)
assert BinaryOperation(symbol <=, RObject 2, 3)
assert BinaryOperation(symbol <=, 2, RObject 3)
assert BinaryOperation(symbol >, RObject 3, RObject 2)
assert BinaryOperation(symbol >, RObject 3, 2)
assert BinaryOperation(symbol >, 3, RObject 2)
assert BinaryOperation(symbol >=, RObject 3, RObject 2)
assert BinaryOperation(symbol >=, RObject 3, 2)
assert BinaryOperation(symbol >=, 3, RObject 2)
assert BinaryOperation(symbol !=, RObject 2, RObject 3)
assert BinaryOperation(symbol !=, RObject 2, 3)
assert BinaryOperation(symbol !=, 2, RObject 3)
