assert Equation(+RObject 1, RObject 1)
assert Equation(-RObject 1, RObject(-1))
assert Equation(abs RObject(-1), RObject 1)
assert Equation(acos RObject 1, RObject 0)
assert Equation(acosh RObject 1, RObject 0)
assert Equation(asin RObject 0, RObject 0)
assert Equation(asinh RObject 0, RObject 0)
assert Equation(atan RObject 0, RObject 0)
assert Equation(atanh RObject 0, RObject 0)
assert Equation(ceiling RObject 2.5, RObject 3)
assert Equation(cos RObject 0, RObject 1)
assert Equation(cosh RObject 0, RObject 1)
assert Equation(exp RObject 0, RObject 1)
assert Equation(expm1 RObject 0, RObject 0)
assert Equation(floor RObject 2.5, RObject 2)
assert Equation(log RObject 1, RObject 0)
assert Equation(log1p RObject 0, RObject 0)
assert Equation(max RObject {1, 3, 5}, RObject 5)
assert Equation(min RObject {1, 3, 5}, RObject 1)
assert Equation(round RObject 2.6, RObject 3)
assert Equation(sin RObject 0, RObject 0)
assert Equation(sinh RObject 0, RObject 0)
assert Equation(sqrt RObject 1, RObject 1)
assert Equation(sum RObject {1, 3, 5}, RObject 9)
assert Equation(tan RObject 0, RObject 0)
assert Equation(tanh RObject 0, RObject 0)
assert Equation((RObject 1)!, RObject 1)
assert Equation(~RObject 1, RObject(-2))
assert Equation(conjugate RObject ii, RObject(-ii))
assert(abs(Digamma RObject 1 + RObject EulerConstant) <
    RObject(1e-15))
assert Equation(Gamma RObject 1, RObject 1)
assert Equation(imaginaryPart RObject ii, RObject 1)
assert Equation(lngamma RObject 1, RObject 0)
assert Equation(product RObject {1, 3, 5}, RObject 15)
assert Equation(realPart RObject ii, RObject 0)
assert Equation(truncate RObject 2.5, RObject 2)
assert Equation(value((RObject 1):(RObject 5)), {1, 2, 3, 4, 5})
assert Equation(value((RObject 1):5), {1, 2, 3, 4, 5})
assert Equation(value((RObject 1)..(RObject 5)), {1, 2, 3, 4, 5})
assert Equation(value((RObject 1)..5), {1, 2, 3, 4, 5})
assert Equation(value(1..(RObject 5)), {1, 2, 3, 4, 5})
assert Equation(RObject 3 & RObject 5, RObject 1)
assert Equation(RObject 3 & 5, RObject 1)
assert Equation(3 & RObject 5, RObject 1)
assert Equation(RObject 3 | RObject 5, RObject 7)
assert Equation(RObject 3 | 5, RObject 7)
assert Equation(3 | RObject 5, RObject 7)
assert Equation(RObject 3 ^^ RObject 5, RObject 6)
assert Equation(RObject 3 ^^ 5, RObject 6)
assert Equation(3 ^^ RObject 5, RObject 6)
assert Equation(RObject 3 << RObject 5, RObject 96)
assert Equation(RObject 3 << 5, RObject 96)
assert Equation(3 << RObject 5, RObject 96)
assert Equation(RObject 10 >> RObject 1, RObject 5)
assert Equation(RObject 10 >> 1, RObject 5)
assert Equation(10 >> RObject 1, RObject 5)
assert Equation(atan2(RObject 0, RObject 1), RObject 0)
assert Equation(atan2(RObject 0, 1), RObject 0)
assert Equation(atan2(0, RObject 1), RObject 0)
assert Equation(Beta(RObject 1, RObject 1), RObject 1)
assert Equation(Beta(RObject 1, 1), RObject 1)
assert Equation(Beta(1, RObject 1), RObject 1)
assert Equation(binomial(RObject 1, RObject 1), RObject 1)
assert Equation(binomial(RObject 1, 1), RObject 1)
assert Equation(binomial(1, RObject 1), RObject 1)
assert Equation(round(RObject 2.567, 2), RObject 2.57)
assert Equation(round(RObject 2.567, digits => 2), RObject 2.57)
