assert Equation(RObject true and RObject true, RObject true)
assert Equation(RObject true and true, RObject true)
assert Equation(true and RObject true, RObject true)
assert Equation(RObject true or RObject true, RObject true)
assert Equation(RObject true or true, RObject true)
assert Equation(true or RObject true, RObject true)
assert Equation(RObject true xor RObject true, RObject false)
assert Equation(RObject true xor true, RObject false)
assert Equation(true xor RObject true, RObject false)
assert Equation(not RObject true, RObject false)
assert Equation(RObject false and NA, RObject false)
assert Equation(RObject true or NA, RObject true)
