F4_CCFILES := \
  f4 \
  f4-monlookup \
  f4-types \
  f4-computation \
  f4-spairs \
  f4-m2-interface \
  monhashtable \
  monsort \
  moninfo \
  ntuple-monomial \
  varpower-monomial \
  gausser

F4_CFILES := 
F4_FILES := $(F4_CCFILES) $(F4_CFILES)
F4_OBJECT_FILES :=  $(addsuffix .o, $(F4_FILES))
