Import('setLibSpecific',
       'setLibSpecificStateEnvExport','setLibSpecificConfigExport','setLibSpecificMakeExport','setLibSpecificMakeInstallExport','setLibSpecificNumStages','setLibSpecificStageCommandArguments',
       'setLibSpecificStageCommand','buildBuilders')

#set this to library name
libraryName = 'mpir'
#Library specific declarations go here.
setLibSpecific('all','all',libraryName,'downloadPath','http://www.mpir.org/')
setLibSpecific('all','all',libraryName,'CompressedLib','mpir-2.4.0.tar.bz2')
setLibSpecific('all',['linux-x86','linux-x86_64','Darwin-x86_64'],libraryName,'InstallFiles',['$SConsInstallPrefixPath/lib/libmpir.a'])
setLibSpecific('all','all',libraryName,'DecompressLib',True)
setLibSpecific('all','all',libraryName,'allowsystem',False)
setLibSpecific('all','all',libraryName,'systemcincludes',['gmp.h'])
setLibSpecific('all','all',libraryName,'systemlibs',['gmp','gmpxx'])
setLibSpecificNumStages('all','all',libraryName,3)
setLibSpecificConfigExport('all',['linux-x86','linux-x86_64'],libraryName,'CC','gcc')
setLibSpecificConfigExport('all',['linux-x86','linux-x86_64'],libraryName,'CXX','g++')
setLibSpecificConfigExport('all',['Darwin-x86_64'],libraryName,'CC','gcc -m64')
setLibSpecificConfigExport('all',['Darwin-x86_64'],libraryName,'CXX','g++ -m64')
setLibSpecificConfigExport('all',['linux-x86'],libraryName,'ABI','32')
setLibSpecificStageCommandArguments('all','all',libraryName,0,['--enable-gmpcompat','--enable-cxx','--disable-shared','--prefix=$SConsInstallPrefixPath'])
setLibSpecific('all','all',libraryName,'enableParallelSubBuild',True)
   
buildBuilders(libraryName)
