import os.path
Import('state','getState','setState','getLibSpecific','setLibSpecific','architecture','numberSubTasks',
        'setLibSpecificStateEnvExport','setLibSpecificConfigExport','setLibSpecificMakeExport','setLibSpecificMakeInstallExport','setLibSpecificNumStages','setLibSpecificStageCommandArguments',
        'setLibSpecificStageCommand','getLibSpecificStageEnvExport','getLibSpecificConfigEnv','getLibSpecificMakeEnv','getLibSpecificMakeInstallEnv','getLibSpecificNumStages','getLibSpecificStageCommandArguments',
        'getLibSpecificStageCommand','getLibSpecificEnv','Glob','exportDict','mode')

efiles = Glob('*.c','.')
eflags = '-I'+getState(mode,architecture,'prefixpath')+'include/ -DNO_CONFIG '+getState(mode,architecture,'eflags')
eobjects = []
#for f in efiles:
#    eobjects.append(Object(f,CFLAGS=cflags))
state[architecture][mode]['efiles']=eobjects


