doc ///
Key
    centerRing
    (centerRing, Ring)
Headline
    compute the center of a ring
Usage
    z = centerRing R
Inputs
    R:Ring
Outputs
    z:RingMap
        $Z \rightarrow R$ the inclusion of the center of $R$ into $R$
Description
    Text
        The center of a ring $R$ is the subring consisting of all the elements that commute with every element of $R$.
    Text
        This method can compute the center of a pure exterior algebra over a field. The center of such a ring consists of the even-degree part
        and so it is generated by products of pairs of the skew variables.
    Example
        kk = ZZ/3
        R = kk[a..d, SkewCommutative => true]
        inc = centerRing R;
        Z = source inc;
        netList (ideal Z)_*
    Text
        The variables in the center are doubly-indexed according to the pairs of
        variables in $R$ that they map to.
    Example
        netList apply(Z_*, i -> i => inc i)
    Text
        Works for towers of rings mixing skew and commutative variables.
    Example
        kk = ZZ/3
        R = kk[a]
        S = R[x..z, SkewCommutative => true]
        inc = centerRing  S;
        Z = source inc;
        netList (ideal Z)_*
    Text
        When $R$ is commutative, this just computes the identity map $R \rightarrow R$.
    Example
        kk = ZZ/5
        assert(centerRing kk === id_kk)

        R = ZZ/5[a..c] / ideal {a^2 + b, b^2 + c^3, c^2 - a*b^2}
         assert(centerRing R === id_R)
Caveat
    Currently only supports commutative rings and skew affine rings.
SeeAlso
    isCommutative
    isSkewAffineRing
///