# -*- makefile-gmake -*-
BIBASIS_FILES = \
	bibasis \
	allocator \
	launcher \
	monom \
	monomDL \
	monomDRL \
	monomLex \
	settings-manager
BIBASIS_CCFILES := $(addsuffix .cpp,$(BIBASIS_FILES))
BIBASIS_DEPFILES := $(addsuffix .dep,$(BIBASIS_FILES))
BIBASIS_OFILES := $(addsuffix .o,$(BIBASIS_FILES))
