P = Proj(QQ[a,b,c])
TP = tangentSheaf(P)
HH^0(TP(-1))
HH^1(TP(-3))
Node = Proj(QQ[a,b,c]/ideal(b^2*c-a^2*(a+c)))
Cusp = Proj(QQ[a,b,c]/ideal(b^2*c-a^3))
TNode = tangentSheaf(Node)
HH^0(TNode)
HH^1(TNode)
TCusp = tangentSheaf(Cusp)
HH^0(TCusp)
HH^1(TCusp)
