Import('setLibSpecific',
       'setLibSpecificStateEnvExport','setLibSpecificConfigExport','setLibSpecificMakeExport','setLibSpecificMakeInstallExport','setLibSpecificNumStages','setLibSpecificStageCommandArguments',
       'setLibSpecificStageCommand','buildBuilders')

#set this to library name
libraryName = 'ntl'
#Library specific declarations go here.
setLibSpecific('all','all',libraryName,'CompressedLib','ntl-5.5.2.tar.gz')
setLibSpecific('all',['linux-x86','linux-x86_64','Darwin-x86_64'],libraryName,'InstallFiles',['$SConsInstallPrefixPath/lib/libntl.a'])
setLibSpecific('all','all',libraryName,'DecompressLib',True)
setLibSpecific('all','all',libraryName,'Dependencies',['gc','mpir','readline','gdbm','mpfr','cddlib','glpk','nauty','4ti2','lapack','lrslib','mpir','pari','cddplus','frobby','gfan','normaliz','boost','scc','libxml2'])
setLibSpecificNumStages('all','all',libraryName,3)
setLibSpecificStageCommandArguments('release',['linux-x86','linux-x86_64'],libraryName,0,['NTL_GMP_LIP=on','NTL_STD_CXX=on','NTL_NO_INIT_TRANS=on','NTL_CXX_ONLY=on','CC=g++','CXX=g++','CFLAGS=-g -O2 -I$SConsInstallPrefixPath/include/','LDFLAGS=-L$SConsInstallPrefixPath/lib/','PREFIX=$SConsInstallPrefixPath'])
setLibSpecificStageCommandArguments('debug',['linux-x86','linux-x86_64'],libraryName,0,['NTL_GMP_LIP=on','NTL_STD_CXX=on','NTL_NO_INIT_TRANS=on','NTL_CXX_ONLY=on','CC=g++','CXX=g++','CFLAGS=-g -O0 -I$SConsInstallPrefixPath/include/','LDFLAGS=-L$SConsInstallPrefixPath/lib/','PREFIX=$SConsInstallPrefixPath'])
setLibSpecificStageCommandArguments('release',['Darwin-x86_64'],libraryName,0,['NTL_GMP_LIP=on','NTL_STD_CXX=on','NTL_NO_INIT_TRANS=on','NTL_CXX_ONLY=on','CC=g++ -m64','CXX=g++ -m64','CFLAGS=-g -O2 -I$SConsInstallPrefixPath/include/','LDFLAGS=-L$SConsInstallPrefixPath/lib/','PREFIX=$SConsInstallPrefixPath'])
setLibSpecificStageCommandArguments('debug',['Darwin-x86_64'],libraryName,0,['NTL_GMP_LIP=on','NTL_STD_CXX=on','NTL_NO_INIT_TRANS=on','NTL_CXX_ONLY=on','CC=g++ -m64','CXX=g++ -m64','CFLAGS=-g -O0 -I$SConsInstallPrefixPath/include/','LDFLAGS=-L$SConsInstallPrefixPath/lib/','PREFIX=$SConsInstallPrefixPath'])
setLibSpecific('all','all',libraryName,'patchfile','../../../../../libraries/ntl/patch-5.5.2')
setLibSpecific('all','all',libraryName,'builddirectory','src/')

buildBuilders(libraryName)
