import os.path
import shutil
import subprocess
Import('state','extractPackageName','extractPackageBaseName','getLibSpecific','setLibSpecific','getState','setState','untarLibrary','transferEnv',
       'configureLibrary','makeLibrary','makeInstallLibrary','deepCleanLibrary','cleanLibrary','architecture',
       'setLibSpecificStateEnvExport','setLibSpecificConfigExport','setLibSpecificMakeExport','setLibSpecificMakeInstallExport','setLibSpecificNumStages','setLibSpecificStageCommandArguments',
       'setLibSpecificStageCommand','getLibSpecificStageEnvExport','getLibSpecificConfigEnv','getLibSpecificMakeEnv','getLibSpecificMakeInstallEnv','getLibSpecificNumStages','getLibSpecificStageCommandArguments',
       'getLibSpecificStageCommand')

#set this to library name
libraryName = 'ntl'
#Library specific declarations go here.
setLibSpecificStageCommandArguments('release',['linux-x86','linux-x86_64'],libraryName,0,['NTL_GMP_LIP=on','NTL_STD_CXX=on','NTL_NO_INIT_TRANS=on','NTL_CXX_ONLY=on','CC=g++','CXX=g++','CFLAGS=-g -O2 -I$SConsInstallPrefixPath/include/','LDFLAGS=-L$SConsInstallPrefixPath/lib/','PREFIX=$SConsInstallPrefixPath'])
setLibSpecificStageCommandArguments('debug',['linux-x86','linux-x86_64'],libraryName,0,['NTL_GMP_LIP=on','NTL_STD_CXX=on','NTL_NO_INIT_TRANS=on','NTL_CXX_ONLY=on','CC=g++','CXX=g++','CFLAGS=-g -O0 -I$SConsInstallPrefixPath/include/','LDFLAGS=-L$SConsInstallPrefixPath/lib/','PREFIX=$SConsInstallPrefixPath'])
setLibSpecific('all','all',libraryName,'patchfile','../../../libraries/ntl/patch-5.5.2')
setLibSpecific('all','all',libraryName,'builddirectory','src/')

def BuildLibrary(target,source,env):
   """
   Build target for the library.
   """
   source = source[0].rstr()
   sourceFile = os.path.split(source)[1]
   packageName = extractPackageName(sourceFile)
   cleaned = CleanLibrary(env.mode,architecture,libraryName)
   untarLibrary(env.state,env.mode,architecture,source, packageName, libraryName)
   configureLibrary(env.state,env.mode,architecture,source,packageName,libraryName)
   makeLibrary(env.state,env.mode,architecture,source,packageName,libraryName)
   makeInstallLibrary(env.state,env.mode,architecture,source,packageName,libraryName)
   return None
   

def CleanLibrary(mode,directory,packageBaseName):
   """
   Actual function that gets called to process a clean library command
   """
   if(deepCleanLibrary(mode,architecture,libraryName)):
      return True
   if(cleanLibrary(mode,architecture,libraryName)):
      return True   
   return False

for mode in state[architecture]['modes']:
   if(getState(mode,architecture,'build')):
      builder = Builder(action=BuildLibrary, single_source=1)
      getState(mode,architecture,'env').Append(BUILDERS = {'build_'+libraryName : builder})
      if(state[architecture][mode].get('builders')==None):
         setState(mode,architecture,'builders',{})
      getState(mode,architecture,'builders')[libraryName]=builder
