import os.path
import shutil
import subprocess
Import('extractPackageName','extractPackageBaseName','getLibSpecific','setLibSpecific','untarLibrary','transferEnv',
       'configureLibrary','makeLibrary','makeInstallLibrary','deepCleanLibrary','cleanLibrary',
       'setLibSpecificStateEnvExport','setLibSpecificConfigExport','setLibSpecificMakeExport','setLibSpecificMakeInstallExport','setLibSpecificNumStages','setLibSpecificStageCommandArguments',
       'setLibSpecificStageCommand','getLibSpecificStageEnvExport','getLibSpecificConfigEnv','getLibSpecificMakeEnv','getLibSpecificMakeInstallEnv','getLibSpecificNumStages','getLibSpecificStageCommandArguments',
       'getLibSpecificStageCommand','defaultCleanLibrary','installBuilders')

#set this to library name
libraryName = 'cddplus'
#Library specific declarations go here.
setLibSpecific('all','all',libraryName,'CompressedLib','cdd+-077a.tar.gz')
setLibSpecific('all',['linux-x86','linux-x86_64','Darwin-x86','Darwin-x86_64'],libraryName,'InstallFiles',['$SConsInstallPrefixPath/bin/cddr+'])
setLibSpecific('all','all',libraryName,'DecompressLib',True)
setLibSpecific('all','all',libraryName,'Dependencies',['cddlib'])
setLibSpecificNumStages('all','all',libraryName,2)

setLibSpecificMakeExport('all',['linux-x86','linux-x86_64','Darwin-x86'],libraryName,'CC','gcc')
setLibSpecificMakeExport('all',['linux-x86','linux-x86_64','Darwin-x86'],libraryName,'CXX','g++')
setLibSpecificMakeExport('all',['Darwin-x86_64'],libraryName,'CC','gcc -m64')
setLibSpecificMakeExport('all',['Darwin-x86_64'],libraryName,'CXX','g++ -m64')
setLibSpecificStageCommandArguments('release','all',libraryName,1,[ 'prefix=$SConsInstallPrefixPath','LDFLAGS=-L$SConsInstallPrefixPath/lib/', 'CFLAGS=-I. -I$SConsInstallPrefixPath/include/ -g -O3',
                                                                'CPPFLAGS=-I. -I$SConsInstallPrefixPath -g -O3', 'all'])
setLibSpecificStageCommandArguments('debug','all',libraryName,1,[ 'prefix=$SConsInstallPrefixPath','LDFLAGS=-L$SConsInstallPrefixPath/lib/', 'CFLAGS=-I. -I$SConsInstallPrefixPath/include/ -g -O0',
                                                                'CPPFLAGS=-I. -I$SConsInstallPrefixPath -g -O0', 'all'])

setLibSpecific('all','all',libraryName,'patchfile','../../../../../libraries/cddplus/patch-077a')
setLibSpecific('all','all',libraryName,'enableParallelSubBuild',True)
   
def BuildLibrary(target,source,env):
   """
   Build target for the library.
   """
   buildSettings = env.buildSettings
   source = source[0].rstr()
   sourceFile = os.path.split(source)[1]
   packageName = extractPackageName(sourceFile)
   cleaned = defaultCleanLibrary(buildSettings,libraryName)
   untarLibrary(buildSettings,source, packageName, libraryName)
   if(buildSettings.getLibSpecific(libraryName,'stage0')):
      buildSettings.setLibSpecific(libraryName,'stage1',True)
   else:
      return None
   if makeLibrary(buildSettings,source,packageName,libraryName):
      buildpath = buildSettings.getBuildPath()
      realpath = buildpath+packageName+'/'
   #install...
      try:
         os.makedirs(os.path.abspath(buildSettings.getPrefixPath()+'/bin'))
      except:
         None
      for target in 'cddr+ cddf+'.split(' '):
         shutil.copy2(realpath+target,os.path.abspath(buildSettings.getPrefixPath()+'/bin/'+target))
   return None
   
installBuilders(BuildLibrary,libraryName)
