Import('setArchitectureState','getLibSpecific','setLibSpecific','numberSubTasks',
        'setLibSpecificStateEnvExport','setLibSpecificConfigExport','setLibSpecificMakeExport','setLibSpecificMakeInstallExport','setLibSpecificNumStages','setLibSpecificStageCommandArguments',
        'setLibSpecificStageCommand','getLibSpecificStageEnvExport','getLibSpecificConfigEnv','getLibSpecificMakeEnv','getLibSpecificMakeInstallEnv','getLibSpecificNumStages','getLibSpecificStageCommandArguments',
        'getLibSpecificStageCommand','getLibSpecificEnv','Glob','exportDict','buildSettings')

objFiles = []
SConscript('c/SConscript',exports=exportDict)
objFiles+=SConscript('regex/SConscript',exports=exportDict)
objFiles+=SConscript('d/SConscript',exports=exportDict)
objFiles+=SConscript('platform/SConscript',exports=exportDict)
objFiles+=SConscript('system/SConscript',exports=exportDict)
objFiles+=SConscript('e/SConscript',exports=exportDict)

libs = ['lapack','blas','fac','cf','cfmem','ntl','gdbm','gc','mpfr','frobby','pari','mpirxx','mpir','readline','history','xml2','z','m','ncurses','gfortran','dl','rt','m','pthread']
m2 = Program(target='M2',source = objFiles,LIBS=libs,LIBPATH='#'+buildSettings.getPrefixPath()+'lib/')
buildSettings.setState('m2',m2)
