import os.path
Import('state','getState','setArchitectureState','getLibSpecific','setLibSpecific','numberSubTasks',
        'setLibSpecificStateEnvExport','setLibSpecificConfigExport','setLibSpecificMakeExport','setLibSpecificMakeInstallExport','setLibSpecificNumStages','setLibSpecificStageCommandArguments',
        'setLibSpecificStageCommand','getLibSpecificStageEnvExport','getLibSpecificConfigEnv','getLibSpecificMakeEnv','getLibSpecificMakeInstallEnv','getLibSpecificNumStages','getLibSpecificStageCommandArguments',
        'getLibSpecificStageCommand','getLibSpecificEnv','Glob','exportDict','buildSettings')

efiles = Glob("*.cpp",".")
buildpath = buildSettings.getBuildPath()+'Macaulay2/system/'
prefixPath = buildSettings.getPrefixPath()
eflags = "-I"+buildpath+"../d/ -IMacaulay2/platform/ -IMacaulay2/d/ -IMacaulay2/e -IMacaulay2/e-includes -I"+prefixPath+"include/ -I"+prefixPath+"include/libxml2/ -IMacaulay2/c/ -IMacaulay2/m2-includes -IMacaulay2/system "+getState(buildSettings,'eflags')
eobjects = []
dpthread = getState(buildSettings,'dFileDict')['pthread.d']
dm2 = getState(buildSettings,'dFileDict')['M2.d']
dinterp = getState(buildSettings,'dFileDict')['interp.d']
for f in efiles:
    obj = Object(f,CFLAGS=eflags,CXXFLAGS=eflags)
    eobjects.append(obj)
    Depends(obj,dpthread)
    Depends(obj,dm2)
    Depends(obj,dinterp)
    
setArchitectureState(buildSettings,'systemfiles',eobjects)
Return('eobjects')

