#ifndef _SYSTEM_TYPEDEFS_H_
#define _SYSTEM_TYPEDEFS_H_

typedef struct M2_string_struct * M2_string;
typedef struct M2_arrayint_struct * M2_arrayint;
typedef M2_arrayint M2_arrayintOrNull;
typedef struct M2_stringCell_struct * M2_stringCell;
typedef struct M2_ArrayString_struct * M2_ArrayString;
typedef M2_ArrayString M2_ArrayStringOrNull;
typedef char * M2_charstar;
typedef unsigned char * M2_ucharstar;
typedef char ** M2_charstarstar;
typedef const char * M2_constcharstar;
typedef const unsigned char * M2_constucharstar;
typedef const char ** M2_constcharstarstar;
typedef char * M2_charstarOrNull;
typedef const char * M2_constcharstarOrNull;
typedef const unsigned char * M2_constucharstarOrNull;
typedef const char ** M2_constcharstarstarOrNull;

typedef struct parse_TokenFile_struct * parse_TokenFile;
typedef struct parse_parseinfo_struct * parse_parseinfo;
typedef struct parse_parsefuns_struct * parse_parsefuns;
typedef struct parse_Word_struct * parse_Word;
typedef struct parse_Symbol_struct * parse_Symbol;
typedef struct parse_SymbolListCell_struct * parse_SymbolListCell;
typedef parse_SymbolListCell parse_SymbolList;
typedef struct parse_SymbolHashTable_struct * parse_SymbolHashTable;
typedef struct parse_Dictionary_struct * parse_Dictionary;
typedef struct parse_Token_struct * parse_Token;
typedef struct parse_Adjacent_struct * parse_Adjacent;
typedef struct parse_For_struct * parse_For;
typedef struct parse_WhileDo_struct * parse_WhileDo;
typedef struct parse_WhileList_struct * parse_WhileList;
typedef struct parse_WhileListDo_struct * parse_WhileListDo;
typedef struct parse_TryElse_struct * parse_TryElse;
typedef struct parse_TryThenElse_struct * parse_TryThenElse;
typedef struct parse_Try_struct * parse_Try;
typedef struct parse_Catch_struct * parse_Catch;
typedef struct parse_IfThen_struct * parse_IfThen;
typedef struct parse_IfThenElse_struct * parse_IfThenElse;
typedef struct parse_New_struct * parse_New;
typedef struct parse_Arrow_struct * parse_Arrow;
typedef struct parse_Quote_struct * parse_Quote;
typedef struct parse_GlobalQuote_struct * parse_GlobalQuote;
typedef struct parse_ThreadQuote_struct * parse_ThreadQuote;
typedef struct parse_LocalQuote_struct * parse_LocalQuote;
typedef struct parse_Binary_struct * parse_Binary;
typedef struct parse_Unary_struct * parse_Unary;
typedef struct parse_Postfix_struct * parse_Postfix;
typedef struct parse_ArrayParseTree_struct * parse_ArrayParseTree;
typedef struct parse_Parentheses_struct * parse_Parentheses;
typedef struct parse_EmptyParentheses_struct * parse_EmptyParentheses;
typedef struct parse_dummy_struct * parse_dummy;
typedef struct parse_StartDictionary_struct * parse_StartDictionary;
typedef struct tagged_union * parse_ParseTree;
typedef struct parse_localSymbolClosureCode_struct * parse_localSymbolClosureCode;
typedef struct parse_globalSymbolClosureCode_struct * parse_globalSymbolClosureCode;
typedef struct parse_threadSymbolClosureCode_struct * parse_threadSymbolClosureCode;
typedef struct parse_localMemoryReferenceCode_struct * parse_localMemoryReferenceCode;
typedef struct parse_globalMemoryReferenceCode_struct * parse_globalMemoryReferenceCode;
typedef struct parse_threadMemoryReferenceCode_struct * parse_threadMemoryReferenceCode;
typedef struct parse_localAssignmentCode_struct * parse_localAssignmentCode;
typedef struct parse_globalAssignmentCode_struct * parse_globalAssignmentCode;
typedef struct parse_ifCode_struct * parse_ifCode;
typedef struct parse_tryCode_struct * parse_tryCode;
typedef struct parse_catchCode_struct * parse_catchCode;
typedef struct parse_SymbolSequence_struct * parse_SymbolSequence;
typedef struct parse_parallelAssignmentCode_struct * parse_parallelAssignmentCode;
typedef struct parse_nullCode_struct * parse_nullCode;
typedef struct parse_realCode_struct * parse_realCode;
typedef struct parse_integerCode_struct * parse_integerCode;
typedef struct parse_stringCode_struct * parse_stringCode;
typedef struct parse_unaryCode_struct * parse_unaryCode;
typedef struct parse_binaryCode_struct * parse_binaryCode;
typedef struct parse_adjacentCode_struct * parse_adjacentCode;
typedef struct parse_whileDoCode_struct * parse_whileDoCode;
typedef struct parse_whileListCode_struct * parse_whileListCode;
typedef struct parse_whileListDoCode_struct * parse_whileListDoCode;
typedef struct parse_ternaryCode_struct * parse_ternaryCode;
typedef struct parse_newOfFromCode_struct * parse_newOfFromCode;
typedef struct parse_newFromCode_struct * parse_newFromCode;
typedef struct parse_newOfCode_struct * parse_newOfCode;
typedef struct parse_newCode_struct * parse_newCode;
typedef struct parse_CodeSequence_struct * parse_CodeSequence;
typedef struct parse_sequenceCode_struct * parse_sequenceCode;
typedef struct parse_listCode_struct * parse_listCode;
typedef struct parse_arrayCode_struct * parse_arrayCode;
typedef struct parse_semiCode_struct * parse_semiCode;
typedef struct parse_multaryCode_struct * parse_multaryCode;
typedef struct parse_forCode_struct * parse_forCode;
typedef struct parse_newLocalFrameCode_struct * parse_newLocalFrameCode;
typedef struct parse_functionDescription_struct * parse_functionDescription;
typedef struct parse_functionCode_struct * parse_functionCode;
typedef struct tagged_union * parse_Code;
typedef struct parse_CodeClosure_struct * parse_CodeClosure;
typedef struct parse_CompiledFunction_struct * parse_CompiledFunction;
typedef struct parse_CompiledFunctionClosure_struct * parse_CompiledFunctionClosure;
typedef struct parse_CompiledFunctionBody_struct * parse_CompiledFunctionBody;
typedef struct parse_Sequence_struct * parse_Sequence;
typedef struct parse_Frame_struct * parse_Frame;
typedef struct parse_FrameLocation_struct * parse_FrameLocation;
typedef struct parse_DictionaryClosure_struct * parse_DictionaryClosure;
typedef struct parse_FunctionClosure_struct * parse_FunctionClosure;
typedef struct parse_SymbolClosure_struct * parse_SymbolClosure;
typedef struct parse_SymbolBody_struct * parse_SymbolBody;
typedef struct parse_List_struct * parse_List;
typedef struct parse_Error_struct * parse_Error;
typedef struct parse_Database_struct * parse_Database;
typedef struct parse_SpecialExpr_struct * parse_SpecialExpr;
typedef struct parse_Boolean_struct * parse_Boolean;
typedef struct parse_Nothing_struct * parse_Nothing;
typedef struct _object * parse_pythonObject;
typedef struct parse_pythonObjectCell_struct * parse_pythonObjectCell;
typedef struct parse_TaskCellBody_struct * parse_TaskCellBody;
typedef struct parse_TaskCell_struct * parse_TaskCell;
typedef struct tagged_union * parse_Expr;
typedef struct parse_KeyValuePair_struct * parse_KeyValuePair;
typedef struct parse_HashTable_struct * parse_HashTable;
typedef struct M2File* parse_m2cfile;
typedef struct parse_file_struct * parse_file;
typedef struct parse_PosFile_struct * parse_PosFile;

typedef struct varstrin_varstring_struct * varstrin_varstring;
typedef varstrin_varstring errio_BasicFile;

typedef struct stdiop0_Position_struct * stdiop0_Position;

class M2CPP_Interperter;
class M2CPP_InterperterLocal;

#endif
