--- status: TODO
--- author(s): 
--- notes: 

document { 
     Key => on,
     Headline => "",
     Usage => "",
     Inputs => {
	  },
     Outputs => {
	  },
     Consequences => {
	  },     
     "description",
     EXAMPLE {
	  },
     Caveat => {},
     SeeAlso => {}
     }
document { 
     Key => [on, CallLimit],
     Headline => "",
     Usage => "",
     Inputs => {
	  },
     Consequences => {
	  },     
     "description",
     EXAMPLE {
	  },
     Caveat => {},
     SeeAlso => {}
     }
document { 
     Key => [on, Name],
     Headline => "",
     Usage => "",
     Inputs => {
	  },
     Consequences => {
	  },     
     "description",
     EXAMPLE {
	  },
     Caveat => {},
     SeeAlso => {}
     }
 -- doc.m2:226:     Key => "recursionLimit",
 -- doc.m2:248:     Key => toString symbol environment,
 -- doc.m2:255:     Key => Function,
 -- doc.m2:345:     Key => maxPosition,
 -- doc.m2:350:     Key => (maxPosition,BasicList),
 -- doc.m2:364:     Key => minPosition, Headline => "position of smallest element" }
 -- doc.m2:366:     Key => (minPosition,BasicList),
 -- doc.m2:443:     Key => (apply,BasicList,BasicList,Function),
 -- doc.m2:453:     Key => (apply,BasicList,Function),
 -- doc.m2:469:     Key => (apply,HashTable,Function),
 -- doc.m2:477:     Key => (apply,ZZ,Function),
 -- doc.m2:497:     Key => (scan,BasicList,Function),
 -- doc.m2:505:     Key => (scan,ZZ,Function),
 -- doc.m2:523:     Key => (scanPairs,HashTable,Function),
 -- doc.m2:542:     Key => (select,BasicList,Function),
 -- doc.m2:557:     Key => (select,HashTable,Function),
 -- doc.m2:567:     Key => (select,ZZ,BasicList,Function),
 -- doc.m2:578:     Key => (select,ZZ,HashTable,Function),
 -- doc.m2:759:     Key => ascii, Headline => "ASCII character conversion" }
 -- doc.m2:794:     Key => (symbol " ", Function, Thing),
 -- doc1.m2:13:     Key => briefDocumentation,
 -- doc1.m2:22:     Key => documentation,
 -- doc1.m2:325:     Key => Option,
 -- doc1.m2:354:     Key => OptionTable,
 -- doc1.m2:358:     Key => (symbol ">>", List, Function),
 -- doc1.m2:363:     Key => (symbol ">>", OptionTable, Function),
 -- doc1.m2:536:     Key => isConstant,
 -- doc1.m2:540:     Key => (isConstant, RingElement),
 -- doc1.m2:630:     Key => leadComponent,
 -- doc1.m2:638:     Key => leadMonomial,
 -- doc1.m2:914:     Key => (options, Function),
 -- doc1.m2:928:     Key => (options, Ring),
 -- doc1.m2:934:     Key => (options, Monoid),
 -- doc1.m2:940:     Key => options, Headline => "get options" }
 -- doc10.m2:15:     Key => Resolution,
 -- doc10.m2:26:     Key => resolution, Headline => "make a projective resolution" }
 -- doc10.m2:28:     Key => [resolution,DegreeLimit],
 -- doc10.m2:46:     Key => [resolution,SyzygyLimit],
 -- doc10.m2:62:     Key => [resolution,PairLimit],
 -- doc10.m2:77:     Key => [resolution,StopBeforeComputation],
 -- doc10.m2:93:     Key => [resolution,LengthLimit],
 -- doc10.m2:119:     Key => [resolution,HardDegreeLimit],
 -- doc10.m2:129:     Key => [resolution,Strategy],
 -- doc10.m2:157:     Key => [resolution,SortStrategy],
 -- doc10.m2:177:     Key => (resolution,Module),
 -- doc10.m2:225:     Key => (resolution, Matrix),
 -- doc10.m2:241:     Key => (resolution, Ideal),
 -- doc10.m2:310:     Key => Monomials,
 -- doc10.m2:342:     Key => CompleteIntersection,
 -- doc10.m2:385:     Key => removeLowestDimension,
 -- doc11.m2:731:     Key => monomialCurveIdeal, 
 -- doc11.m2:943:     Key => Monoid,
 -- doc11.m2:952:     Key => (symbol _, ZZ, Monoid),
 -- doc12.m2:4:     Key => (accumulate, Function, Thing, VisibleList),
 -- doc12.m2:13:     Key => (accumulate, Function, VisibleList),
 -- doc12.m2:22:     Key => (accumulate, VisibleList, Thing, Function),
 -- doc12.m2:28:     Key => (accumulate, VisibleList, Function),
 -- doc12.m2:47:     Key => (fold, Function, Thing, VisibleList),
 -- doc12.m2:52:     Key => (fold, Function, VisibleList),
 -- doc12.m2:60:     Key => (fold, VisibleList, Thing, Function),
 -- doc12.m2:65:     Key => (fold, VisibleList, Function),
 -- doc12.m2:207:     Key => positions,
 -- doc12.m2:220:     Key => position,
 -- doc12.m2:335:     Key => partitions,
 -- doc12.m2:363:     Key => (symbol -, List), Headline => "negation of a vector",
 -- doc12.m2:461:     Key => (sum, List, List, Function),
 -- doc12.m2:475:     Key => (sum, List, Function),
 -- doc12.m2:484:     Key => (sum, ZZ, Function),
 -- doc12.m2:527:     Key => (product, List, List, Function),
 -- doc12.m2:540:     Key => (product, List, Function),
 -- doc12.m2:549:     Key => (product, ZZ, Function),
 -- doc12.m2:632:     Key => AssociativeExpression,
 -- doc12.m2:649:     Key => ZeroExpression,
 -- doc12.m2:656:     Key => OneExpression,
 -- doc12.m2:663:     Key => Expression,
 -- doc12.m2:684:     Key => expression,
 -- doc12.m2:709:     Key => MatrixExpression,
 -- doc12.m2:719:     Key => RowExpression,
 -- doc12.m2:734:     Key => NonAssociativeProduct,
 -- doc12.m2:760:     Key => SparseVectorExpression,
 -- doc12.m2:767:     Key => SparseMonomialVectorExpression,
 -- doc12.m2:777:     Key => BinaryOperation,
 -- doc12.m2:798:     Key => FunctionApplication,
 -- doc12.m2:812:     Key => Equation,
 -- doc2.m2:628:     Key => sin, -- this node is used as an example in the documentation node Inputs and Outputs.
 -- doc2.m2:695:     Key => cosh, Headline => "hyperbolic cosine function",
 -- doc2.m2:700:     Key => tanh, Headline => "hyperbolic tangent function",
 -- doc2.m2:705:     Key => exp, Headline => "exponential function",
 -- doc2.m2:710:     Key => log, Headline => "logarithm function",
 -- doc2.m2:715:     Key => sqrt, Headline => "square root function",
 -- doc2.m2:791:     Key => (value,Expression),
 -- doc2.m2:877:     Key => concatenate,
 -- doc3.m2:19:     Key => FilePosition,
 -- doc3.m2:132:     Key => (symbol /, VisibleList, Function),
 -- doc3.m2:145:     Key => (symbol \,Function, VisibleList),
 -- doc3.m2:241:     Key => horizontalJoin,
 -- doc3.m2:430:     Key => connectionCount,
 -- doc3.m2:507:     Key => "using functions with optional inputs",
 -- doc4.m2:112:     Key => generatorExpressions,
 -- doc4.m2:368:     Key => "version",
 -- doc4.m2:444:     Key => addStartFunction,
 -- doc4.m2:451:     Key => addEndFunction,
 -- doc4.m2:723:     Key => globalAssignFunction,
 -- doc4.m2:751:     Key => globalReleaseFunction,
 -- doc5.m2:96:     Key => on,
 -- doc5.m2:495:     Key => symbol globalDictionaries,
 -- doc5.m2:502:     Key => Dictionary,
 -- doc5.m2:513:     Key => dictionary,
 -- doc6.m2:63:     Key => (ring, MonomialIdeal),
 -- doc6.m2:163:     Key => fraction,
 -- doc6.m2:175:     Key => FractionField,
 -- doc6.m2:280:     Key => conjugate,
 -- doc6.m2:299:     Key => OrderedMonoid,
 -- doc6.m2:346:     Key => exponents,
 -- doc6.m2:512:     Key => MonoidElement,
 -- doc6.m2:537:     Key => MonomialSize,
 -- doc6.m2:557:     Key => GeneralOrderedMonoid,
 -- doc6.m2:566:     Key => (symbol _, Monoid, ZZ),
 -- doc6.m2:572:     Key => degreesMonoid,
 -- doc6.m2:643:     Key => "MonomialOrderOLD",
 -- doc6.m2:660:     Key => MonomialOrder,
 -- doc6.m2:720:     Key => (monoid, Array),
 -- doc6.m2:739:     Key => (symbol " ",Ring, OrderedMonoid),
 -- doc6.m2:745:     Key => (monoid, Ring),
 -- doc6.m2:754:     Key => monoid,
 -- doc6.m2:776:     Key => (symbol **, Monoid, Monoid),
 -- doc6.m2:1018:     Key => relations,
 -- doc6.m2:1108:     Key => components,
 -- doc6.m2:1379:     Key => indexComponents,
 -- doc7.m2:313:     Key => contract,
 -- doc7.m2:318:     Key => (contract,Matrix,Matrix),
 -- doc7.m2:823:     Key => (map,Module,Module,Function),
 -- doc7.m2:1029:     Key => (map,Module,ZZ,Function),
 -- doc7.m2:1563:     Key => content,
 -- doc7.m2:1720:     Key => (symbol _,Function,Thing),
 -- doc7.m2:1748:     Key => MinorsComputation,
 -- doc7.m2:2202:     Key => hilbertFunction,
 -- doc7.m2:2405:     Key => presentation,
 -- doc8.m2:264:     Key => "Monomial orders in free modules",
 -- doc8.m2:516:     Key => StopBeforeComputation,
 -- doc8.m2:523:     Key => [gb,StopBeforeComputation],
 -- doc8.m2:618:     Key => CodimensionLimit,
 -- doc8.m2:637:     Key => [gb,CodimensionLimit], 
 -- doc8.m2:743:     Key => LongPolynomial,
 -- doc8.m2:926:     Key => [syz,CodimensionLimit],
 -- doc8.m2:973:     Key => [syz,StopBeforeComputation],
 -- doc8.m2:1399:     Key => getNonUnit, Headline => "retrieve a previously discovered non-unit",
 -- doc8.m2:1669:     Key => NonLinear,
 -- doc8.m2:1676:     Key => [pushForward1,StopBeforeComputation],
 -- doc8.m2:1765:     Key => [pushForward1,MonomialOrder],
 -- doc8.m2:1781:     Key => [pushForward1,UseHilbertFunction],
 -- doc8.m2:1806:     Key => PushforwardComputation,
 -- doc8.m2:1813:     Key => EliminationOrder,
 -- doc9.m2:16:     Key => [pushForward,StopBeforeComputation],
 -- doc9.m2:56:     Key => UseHilbertFunction,
 -- doc9.m2:181:     Key => MonomialIdeal, 
 -- doc9.m2:210:     Key => (dual,MonomialIdeal,List),
 -- doc9.m2:223:     Key => (dual,MonomialIdeal,RingElement),
 -- doc9.m2:237:     Key => (dual,MonomialIdeal),
 -- doc9.m2:302:     Key => (isSquareFree,MonomialIdeal),
 -- doc9.m2:331:     Key => (standardPairs, MonomialIdeal),
 -- doc9.m2:372:     Key => (monomialSubideal, Ideal),
 -- doc9.m2:390:     Key => monomialIdeal,
 -- doc9.m2:395:     Key => (monomialIdeal, Ideal),
 -- doc9.m2:404:     Key => (monomialIdeal, List),
 -- doc9.m2:413:     Key => (monomialIdeal, Sequence),
 -- doc9.m2:420:     Key => (monomialIdeal, Matrix),
 -- doc9.m2:433:     Key => (monomialIdeal, MonomialIdeal),
 -- doc9.m2:671:document { Key => cone, Headline => "mapping cone of a chain map" }
 -- doc9.m2:673:     Key => (cone,ChainComplexMap),
 -- doc9.m2:1642:     Key => (components, ChainComplex),
 -- doc9.m2:1932:     Key => (map,ChainComplex,ChainComplex,Function),
 -- doc_doc.m2:82:  PRE ///Key => resolution,///,
 -- doc_doc.m2:85:  PRE ///Key => (resolution,Module),///,
 -- doc_doc.m2:88:  PRE ///Key => [resolution,SyzygyLimit],///,
 -- doc_doc.m2:92:          PRE ///Key => "chain complexes",///,
 -- doc_doc.m2:104:     Usage => "document { Key => key, Headline => \"one line description\", ... }",
 -- doc_doc.m2:129: Key => "Function ",
 -- doc_doc.m2:183:     Key => Consequences, 
 -- doc_packages.m2:194:     Key => beginDocumentation,
 -- doc_packages.m2:297:     Key => [installPackage,RemakeAllDocumentation],
 -- normal_doc.m2:100:     Key => (ICfractions,Ring),
 -- normal_doc.m2:122:     Key => (conductor,RingMap),
 -- overview2.m2:206:     Key => "free resolutions of modules",
 -- overview2.m2:229:     Key => "extracting information from chain complexes",
 -- overview2.m2:452:     Key => "functions",
 -- overview2.m2:689:     Key => "using functions",
 -- overview2.m2:726:     Key => "making functions",
 -- overview2.m2:784:     Key => "making functions with a variable number of arguments",
 -- overview2.m2:823:     Key => "making new functions with optional arguments",
 -- overview2.m2:853:     Key => "conditional execution",
 -- overview2.m2:975:     Key => "local variables in a function",
 -- overview2.m2:1725:     Key => "two dimensional formatting",
 -- overview2.m2:1942:     Key => "making a new method function",
 -- overview2.m2:2184:     Key => [method,Options],
 -- overview3.m2:189:     Key => "reading the documentation",
 -- overview3.m2:425:     Key => "Daniel R. Grayson",
 -- overview3.m2:603:     Key => "initialization file",
 -- overview3.m2:623:     Key => "combinatorial functions",
 -- overview4.m2:322:     Key => "component example",
 -- overview4.m2:557:     Key => "diff and contract",
 -- overview4.m2:722:     Key => "computing resolutions",
 -- overviewA.m2:227:     Key => "projections, inclusions, and permutations",
 -- overviewA.m2:233:     Key => "substitution and maps between rings",
 -- overviewA.m2:295:     Key => "chain complexes",
 -- overviewA.m2:326:     Key => "rings that are available for Groebner basis computations",
 -- overviewA.m2:384:     Key => "convex hulls and polar cones",
 -- overviewA.m2:394:     Key => "elimination theory",
 -- overviewA.m2:408:     Key => "Lenstra-Lenstra-Lovasz (LLL) lattice basis reduction",
 -- overviewB.m2:158:     Key => "equality and containment",
 -- overviewB.m2:270:     Key => "dimension, codimension, and degree",
 -- overviewB.m2:285:     Key => "intersection of ideals",
 -- overviewB.m2:295:     Key => "ideal quotients and saturation",
 -- overviewB.m2:449:     Key => "primary decomposition",
 -- overviewB.m2:683:     Key => "basic construction, source and target of a ring map",
 -- overviewB.m2:735:     Key => "evaluation and composition of ring maps",
 -- overviewB.m2:868:     Key => "concatenating matrices",
 -- overviewB.m2:907:     Key => "extracting information about a matrix",
 -- overviewB.m2:1029:     Key => "differentiation",
 -- overviewC.m2:294:     Key => "monomial orderings", 
 -- overviewC.m2:318:     Key => "examples of specifying alternate monomial orders",
 -- overviewC.m2:350:     Key => "monomial orders for free modules",
 -- overviewC.m2:353:     Key => "operations involving monomial orders"
 -- overviewC.m2:356:     Key => "packing monomials for efficiency",
 -- overviewC.m2:375:     Key => "definition of graded reverse lexicographic order: GRevLex",
 -- overviewC.m2:392:     Key => "definition of lexicogrpahic order: Lex",
 -- overviewC.m2:401:     Key => "definition of weight orders: Weights"
 -- overviewC.m2:404:     Key => "definition of elimination orders: Eliminate"
 -- overviewC.m2:407:     Key => "definition of product (block) orders"
 -- overviewC.m2:410:     Key => "obtaining the monomial order of a ring",
 -- overviewC.m2:422:     Key => "monomial orderings1", 
 -- overviewC.m2:481:     Key => "monomial orderingsOLD",
 -- overviewC.m2:876:     Key => "fraction fields",
 -- overviewC.m2:920:     Key => "finite field extensions",
 -- overviewC.m2:1093:     Key => "construction of free modules",
 -- overviewC.m2:1137:     Key => "Hilbert functions and free resolutions",
 -- overviewC.m2:1215:     Key => "operations on modules",
 -- overviewC.m2:1250:     Key => "equality and containment of modules",
 -- overviewC.m2:1255:     Key => "minimal presentations and generators",
 -- overviewC.m2:1275:     Key => "constructing maps between modules",
 -- overviewC.m2:1302:     Key => "information about a map of modules",
 -- overviewC.m2:1316:     Key => "Hilbert functions and polynomials",
 -- overviewC.m2:1320:     Key => "homogenization",
 -- overviewC.m2:1324:     Key => "truncation and homogeneous components of a graded module",
 -- overviewC.m2:1386:     Key => "free resolutions",
 -- overviewC.m2:1407:     Key => "monomial orderings v1.0",
 -- overviewC.m2:1464:     Key => "elimination of variables",
 -- overviewC.m2:1468:     Key => "Hilbert functions",
 -- overviewC.m2:1476:     Key => "saturation",
 -- overviewC.m2:1484:     Key => "solving systems of polynomial equations",
 -- overviewC.m2:1504:     Key => "fine control of a Groebner basis computation",
 -- overview_doc.m2:2:     Key => "writing documentation",
 -- overview_doc.m2:168:     Key => "conventions for documentation",
 -- overview_doc.m2:178:     Key => "function name documentation template",
 -- overview_doc.m2:180:     Key => functionName,
 -- overview_doc.m2:207:     Key => "function documentation template",
 -- overview_doc.m2:209:     Key => (functionName, argumentClass1, argumentClass2, ...),
 -- overview_doc.m2:236:     Key => "optional argument name documentation template",
 -- overview_doc.m2:238:     Key => optionName,
 -- overview_doc.m2:255:     Key => "optional argument documentation template",
 -- overview_doc.m2:257:     Key => [functionName, optionName],
 -- overview_doc.m2:281:     Key => "overview documentation template",
 -- overview_doc.m2:283:     Key => "description of this page",
 -- overview_doc.m2:300:     Key => "package documentation template",
 -- overview_packages.m2:154:       Key => firstFunction,
