assert( (parse "x") === {{"Token","x"}} );
assert( (parse "(x)") === {{"Parentheses",{"Token","("},{"Token","x"},{"Token",")"}}} );
assert( (parse "()") === {{"EmptyParentheses",{"Token","("},{"Token",")"}}} );
assert( (parse "rank x") === {{"Adjacent",{"Token","rank"},{"Token","x"}}} );
assert( (parse "x -> x") === {{"Arrow",{"Token","x"},{"Token","x"}}} );
assert( (parse "symbol x") === {{"Quote",{"Token","x"}}} );
assert( (parse "global x") === {{"GlobalQuote",{"Token","x"}}} );
assert( (parse "threadLocal x") === {{"ThreadQuote",{"Token","x"}}} );
assert( (parse "local x") === {{"LocalQuote",{"Token","x"}}} );
assert( (parse "-x") === {{"Unary",{"Token","-"},{"Token","x"}}} );
assert( (parse "x + y") === {{"Binary",{"Token","x"},{"Token","+"},{"Token","y"}}} );
assert( (parse "x_*") === {{"Postfix",{"Token","x"},{"Token","_*"}}} );
assert( (parse "if x then y") === {{"IfThen",{"Token","x"},{"Token","y"}}} );
assert( (parse "if x then y") === {{"IfThen",{"Token","x"},{"Token","y"}}} );
assert( (parse "if x then y else z") === {{"IfThenElse",{"Token","x"},{"Token","y"},{"Token","z"}}} );
assert( (parse "try x") === {{"Try",{"Token","x"}}} );
assert( (parse "try x then y") === {{"TryThen",{"Token","x"},{"Token","y"}}} );
assert( (parse "try x then y else z") === {{"TryThenElse",{"Token","x"},{"Token","y"},{"Token","z"}}} );
assert( (parse "try x else z") === {{"TryElse",{"Token","x"},{"Token","z"}}} );
assert( (parse "try x then y except z do z") === {{"TryThenDo",{"Token","x"},{"Token","y"},{"Token","z"},{"Token","z"}}} );
assert( (parse "try x except z do z") === {{"TryDo",{"Token","x"},{"Token","z"},{"Token","z"}}} );
assert( (parse "catch x") === {{"Catch",{"Token","x"}}} );
assert( (parse "while x do z") === {{"WhileDo",{"Token","x"},{"Token","z"}}} );
assert( (parse "while x list y do z") === {{"WhileListDo",{"Token","x"},{"Token","y"},{"Token","z"}}} );
assert( (parse "while x list y") === {{"WhileList",{"Token","x"},{"Token","y"}}} );
assert( (parse "for x from y to z when w list a do b") === {{"For",{"Token","x"},{"dummy"},{"Token","y"},{"Token","z"},{"Token","w"},{"Token","a"},{"Token","b"}}} );
assert( (parse "new x of y from z") === {{"New",{"Token","x"},{"Token","y"},{"Token","z"}}} );
assert( (parse "") === {} );
assert( (parse "x;y\nz") === {{"Token","x"},{"Token","y"},{"Token","z"}} );
